cake-tech/cake_wallet

assets/node_list.yml
lib/main.dart
lib/src/domain/common/default_settings_migration.dart
lib/src/domain/common/node_list.dart

Replaced eu-node.cakewallet.io by xmr-node-eu.cakewallet.com and node cakewallet.io by xmr-node-usa-east.cakewallet.com in remote nodes list. Added migration for change current remote node if user use old eu or usa remote node by new addresses. Changed way for set default remote node for initial setup by base on current user time zone.

Changed cake wallet remote nodes addresses and credentials

---

lib/src/stores/address_book/address_book_store.dart
lib/src/stores/exchange/exchange_store.dart
lib/src/stores/send/send_store.dart
lib/src/stores/wallet_restoration/wallet_restoration_store.dart

Beech32 encoded BTC address may have a length of 62 characters, which is used by several apps, e.g. Bitwala.
For reference see:
https://en.bitcoin.it/wiki/BIP_0173#Segwit_address_format

Fix validation for Beech32 encoded BTC address

---

lib/src/screens/new_wallet/new_wallet_page.dart
lib/src/screens/restore/wallet_restore_from_keys_form.dart
lib/src/screens/restore/wallet_restore_from_seed_form.dart

@mkyq , I have added the dismissable-keyboard property to generate-name button. The keyboard was not getting dismissed completely because the button resided inside the TextFormField and so onPress method of the button also triggered the focus on TextFormField and thus invoked the onTap method on TextFormField. However, I have tackled it using Stack to separate the onTap and onPress triggering each other.

soft keyboard dismisses when generate-name icon is pressed

---

lib/src/screens/dashboard/widgets/menu_widget.dart

This is a bug I discovered using the app. It was not assigned as a task. This is why it has no branch name like "'CW-number". Approved by our CTO.

Fixed the render flex error caused by menu widget title in monero wallet

---

lib/core/yat_service.dart
lib/store/yat/yat_store.dart

Just some small fixes here, the api dev url was missing the subdomain `a`.
Instead of showing both the subaddress and the standard address, choose just the sub address and if it's not available use the standard address.

Select sub address or standard address instead of both.

---

lib/view_model/exchange/exchange_view_model.dart

Skip unsupported providers when calculating the best rate provider

Fix unsupported providers in exchange flow

---

lib/core/address_validator.dart

Sideshift only supports `zs` Sapling addresses now. They do not support `zc` Sprout addresses or `u` unified addresses
Validation did not work for `zs` before this change because the code used `&` where it should have used `$`

fix zaddr validation

---

lib/view_model/restore_from_backup_view_model.dart

there is a new error message thrown in 
`/flutter/.pub-cache/hosted/pub.dartlang.org/cryptography-2.0.5/lib/src/cryptography/mac.dart` which is
`SecretBox has wrong message authentication code (MAC)`
so I changed the condition to be more adaptable and focus on the error itself `message authentication code (MAC)`

Adapt error message check in backup errors

---

cw_haven/lib/haven_wallet.dart

Check if the address is parsed then create the transaction with the parsed address not the entered address

Fix FIO send parsed Address

---

lib/src/screens/root/root.dart

Check whether it needs to request auth or not AFTER the user gets back to the app

[CW-280] Fix PIN timeout issue

---

.github/workflows/cache_dependencies.yml
.github/workflows/pr_test_build.yml

- Add Cache Dependencies workflow on main branch to be available for all sub-branches
- Replace static cache key with the hash of dependencies pubspec.yaml

Caching Dependencies in workflow run

---

lib/entities/qr_scanner.dart

Trim the content scanned via QR to remove extra spaces/new lines

Fix Additional characters on scanned QR addresses

---

lib/anypay/anypay_api.dart
lib/utils/exception_handler.dart

- Ignore Socket Exception "bad file descriptor" caused on iOS devices due to sockets getting closed if App is idle or screen lock ([issue ref](https://github.com/dart-lang/http/issues/197))
- Add nullability to anypay API response failure

Exception Handler Enhancements

---

cw_bitcoin/lib/bitcoin_amount_format.dart
cw_core/lib/monero_amount_format.dart

Fix Amount parsed with a slightly different amount due to double not being represented exactly

Fix incorrect amount parsing

---

lib/entities/preferences_key.dart
lib/src/screens/dashboard/dashboard_page.dart
lib/src/screens/settings/display_settings_page.dart
lib/store/settings_store.dart
lib/view_model/dashboard/dashboard_view_model.dart
lib/view_model/settings/display_settings_view_model.dart
res/values/strings_ar.arb
res/values/strings_bg.arb
res/values/strings_cs.arb
res/values/strings_de.arb
res/values/strings_en.arb
res/values/strings_es.arb
res/values/strings_fr.arb
res/values/strings_hi.arb
res/values/strings_hr.arb
res/values/strings_id.arb
res/values/strings_it.arb
res/values/strings_ja.arb
res/values/strings_ko.arb
res/values/strings_my.arb
res/values/strings_nl.arb
res/values/strings_pl.arb
res/values/strings_pt.arb
res/values/strings_ru.arb
res/values/strings_th.arb
res/values/strings_tr.arb
res/values/strings_uk.arb
res/values/strings_ur.arb
res/values/strings_zh.arb

Add switcher in display settings to enable/disable marketplace page
if enabled: it will be the same behavior as it is right now
if disabled: the dashboard screen will only have the balance and transactions screen
- [] Double check modified code and verify it with the feature/task requirements

CW-331-Add-option-to-disable-market-place-in-display-settings

---

ios/Runner/AppDelegate.swift

End editing in ios to dismiss keyboard before app goes to background

CW-362 iOS issue keyboard space is still showing in app

---

cw_bitcoin/lib/electrum.dart

handle multiple responses coming in a single event
sometimes the events we receive in `socket!.listen((Uint8List event)` has more than one RPC response
ex.
```
{"jsonrpc": "2.0", "result": "f2c0cea5f.......1e4ca", "id": "4498"}
{"jsonrpc": "2.0", "result": "d5694e3f........87dd", "id": "4499"}
```
thus failing to parse this event as json, resulting in failure of parsing any response afterwards

Fix Bitcoin transactions not showing

---

lib/buy/onramper/onramper_buy_provider.dart

Updated onramper to use network wallet parameter instead of `wallet`

CW-443 Use networkWallets on OnRamper

---

lib/reactions/fiat_rate_update.dart
lib/view_model/dashboard/balance_view_model.dart

Issue Number (if Applicable): Fixes # CW-441
Fixes CW-441, which was an issue where when enabling the fiat API setting there would not be any price info which would lead to an exception.
Now when the fiat API setting is enabled the timer for fetching fiat data is reset and run immediately, and canceled otherwise.

CW-441 xmr price issue

---

lib/src/widgets/nav_bar.dart

Issue Number (if Applicable): Fixes # CW-440
Fixes a bug where after transitioning between certain routes the nav bar would fail to render for a few frames

fix nav-bar issue

---

lib/entities/openalias_record.dart
lib/entities/parsed_address.dart
lib/src/screens/send/widgets/extract_address_from_parsed.dart
lib/src/screens/send/widgets/send_card.dart
lib/src/widgets/address_text_field.dart
lib/view_model/send/output.dart
pubspec_base.yaml

Cake Wallet now displays the Name of the Contact above the actual wallet address in the send view.
Cake Wallet now ignores false positives on OpenAliasRecords, for domains that don't use OpenAlias.

CW-425 use the open alias new line UI

---

cw_ethereum/lib/default_erc20_tokens.dart

PayPal USD (PYUSD) is disabled by default, to appear only in the token search list.
https://github.com/paxosglobal/pyusd-contract

Add PYUSD to token list [skip ci]

---

cw_monero/lib/api/transaction_history.dart
cw_monero/lib/monero_wallet.dart

Fix Typos and now transactions between accounts show up correctly.

CW-476 Only get Transactions of one Account on tx-history refresh

---

lib/entities/default_settings_migration.dart

1 line change to fix nano pow nodes loading into the nodes page

hotfix nodes page loading in the wrong nodes

---

pubspec_base.yaml
tool/download_moneroc_prebuilds.dart

Whenever you want to build on macos for android, or just don't have enough time to build the entire codebase, in this scenario you can simply execute:
```bash
$ dart run tool/download_moneroc_prebuilds.dart
```
and kickstart the development without copying libraries around.

Script to download prebuilds of monero_c

---

cw_monero/lib/api/transaction_history.dart

It gives user information about the fact that there is something wrong with the node, while still having the entire error available.

monero_c better errors when node fails to respond

---

cw_monero/lib/api/subaddress_list.dart
cw_monero/lib/api/wallet.dart
cw_monero/lib/monero_wallet_addresses.dart
cw_wownero/lib/api/subaddress_list.dart
cw_wownero/lib/wownero_wallet_addresses.dart

This fixes the issue from the report that Omar sent me, as well as fixing a logic issue that was merged earlier...
I believe that the root of the issue of accessing .last / .first elements is this piece of code https://github.com/cake-tech/cake_wallet/blob/e58d87e94cc82e268fc5e5901e4bea47c7c4ce50/cw_monero/lib/monero_subaddress_list.dart#L28-L30 - or in general all the places where it is being set - we leave the variable as temporarily empty. I believe that the proper fix would be to add mutexes around that functions - as this should solve most of the issues (but will make the code async in all places, which may be undesired). For now it should be good.

monero fixes

---

android/app/build.gradle
android/app/src/main/java/com/cakewallet/cake_wallet/MainActivity.java
android/app/src/main/java/com/cakewallet/haven/MainActivity.java
android/app/src/main/java/com/monero/app/MainActivity.java
ios/Podfile
ios/Runner/AppDelegate.swift
lib/entities/unstoppable_domain_address.dart

Removed the dependency on native dependencies and replaced it with a single http call to unstoppable domain's api.
This also makes it possible to use it on desktop platforms

unstoppable domains fix

---

cw_monero/lib/api/wallet.dart
cw_monero/pubspec.lock
cw_monero/pubspec.yaml
cw_wownero/lib/api/wallet.dart
cw_wownero/pubspec.lock
cw_wownero/pubspec.yaml
lib/src/widgets/seed_language_picker.dart
pubspec_base.yaml

Fix legacy seeds not being displayed when polyseed is not supported

---

analysis_options.yaml
tool/download_moneroc_prebuilds.dart

Remove cw_*.dart files from analyzer
So my IDE is full of red, and I have to go and confirm that I do want to debug the app without fixing the errors (VSCode) or hide prompts warning me about that (Android Studio), because of errors in files that are not being used in the wallet.
Pros:
- no analyzer smalltalk for working code
Cons:
- no analyzer smalltalk for when something is wrong in the cw_*.dart files (it will still complain while compiling/running so it should be fine imo)
Also: `dart run tool/download_moneroc_prebuilds.dart` now runs gen_framework.sh to make running iOS app easier.
| With PR | Without |
| ---- | ---- |
| ![obraz](https://github.com/user-attachments/assets/6f6f2d14-6d41-474f-8585-4777b9445708) | ![obraz](https://github.com/user-attachments/assets/bce4cfc5-d34b-4ebf-9d …

make analyzer less red

---

cw_monero/lib/api/transaction_history.dart

This fixes the txkey display, and not show the error

CW-745 don't show txkey when it's unavailable

---

lib/src/screens/dashboard/widgets/sign_form.dart
lib/src/screens/dashboard/widgets/verify_form.dart

Issue Number (if Applicable): Fixes #1643

keep sign/verify pages loaded

---

lib/view_model/wallet_address_list/wallet_address_list_view_model.dart

This fixes a divide with 0 issue on the receive screen
Please test for the following:
Go to the receive screen and select a fiat currency other than your default. 
Now enter a amount and scan the QR code with a other wallet. The fiat value of the amount encoded should correspond with the fiat value entered.

Fix fiat rate on receive screen.

---

lib/reactions/on_current_wallet_change.dart
lib/store/app_store.dart

Potential fix for the race condition of loading a wallet while the name in the shared prefs hasn't updated yet

fix cached wallet race condition

---

tool/utils/secret_key.dart

Fixes error during building 
```bash
#11 527.9 lib/.secrets.g.dart:57:7: Error: Type 'bitco' not found.
#11 527.9 const bitco inCashTestWalletReceiveAddress = '';
#11 527.9       ^^^^^
#11 533.3 lib/.secrets.g.dart:57:7: Error: 'bitco' isn't a type.
#11 533.3 const bitco inCashTestWalletReceiveAddress = '';
#11 533.3       ^^^^^
#11 548.1 Target kernel_snapshot failed: Exception
#11 548.1 
#11 548.2 
#11 548.2 FAILURE: Build failed with an exception.
```
blame: [0fcfd76](https://github.com/cake-tech/cake_wallet/commit/0fcfd76afd75b91665e25804859497aa46a051aa#diff-3e7b3d74f017ddcc2cf3937a053a07142d958550ed7d98921ba928a48a5fce84) :D

Fix Whitespace in secret_key.dart

---

cw_bitcoin/lib/electrum.dart
cw_bitcoin/lib/electrum_wallet.dart
lib/src/screens/unspent_coins/unspent_coins_list_page.dart

Cw 853 mweb utxos are not displayed in coin control screen

---

cw_core/lib/node.dart

Digest authenticated nodes will now show correct status

CW-860 Fix status for http auth nodes

---

tool/download_moneroc_prebuilds.dart

I'm in the process of removing .xz compression of artifacts

fix download monero_c prebuilds issue caused by cleanup

---

cw_decred/lib/api/libdcrwallet.dart
cw_decred/lib/wallet.dart
cw_decred/lib/wallet_service.dart
cw_decred/pubspec.lock
scripts/android/build_decred.sh
scripts/ios/build_decred.sh
scripts/macos/build_decred.sh

The wallet was panicking when viewing keys from watching only. Also the derivationInfo we were using was deprecated. This stops the panic and no longer uses the deprecated property.
Will add more commits for fixing list transacitons time and height if this is up for a while.

decred: Update derivation info.

---

assets/zano_node_list.yml
lib/entities/default_settings_migration.dart
lib/entities/zano_alias.dart
lib/main.dart

migrate zano node to use SSL

---

cw_decred/lib/api/libdcrwallet.dart
cw_decred/lib/wallet.dart
cw_decred/lib/wallet_addresses.dart
cw_decred/lib/wallet_service.dart
cw_decred/pubspec.lock
cw_decred/pubspec.yaml
lib/decred/cw_decred.dart

Attempting to solve the problem pointed out in #2067 but this also seems to make the app more responsive. Still testing.

decred: Run libwallet in isolate.

---

cw_monero/lib/monero_wallet.dart

rename background sync cache file

CW-1025 renaming wallets makes them inaccessible

---

cw_monero/lib/monero_wallet_service.dart

Fix the missing passphrase for the bip39 monero wallets

Fix missing passphrase for bip39 Monero Wallets

---

lib/src/screens/buy/buy_sell_page.dart
lib/src/screens/exchange/widgets/desktop_exchange_cards_section.dart
lib/src/screens/pin_code/pin_code_widget.dart

fix(desktop-pin-code-issue): persist FocusNode so KeyboardListener works on macOS
Previously, every rebuild created a new FocusNode, so KeyboardListener never held focus and missed key events on macOS.
This change:
- Moves the FocusNode into state and initializes it in initState
- Requests focus once after the first frame
- Disposes of the FocusNode in dispose
- Removes the inline FocusNode creation from build

CW-1015: Desktop Issues

---

lib/core/backup_service.dart
tool/configure.dart

If one of the wallets is corrupted backup silently fails. This PR fixes that

fix: allow bakcups to be created even if one of the wallets is corrupted

---

lib/src/screens/restore/wallet_restore_from_seed_form.dart

Issue Number: Fixes #2248
This PR fixes the wordlist selection on the restore from seed screen for Monero Wallets

fix: selection of the wordlist for seed validation on the restore from seed page

---

cw_monero/lib/monero_wallet_service.dart

fix(cw_monero): move isolates to top level functions so WalletBase will not get sent over.

fix(cw_monero): move isolates to top level functions so WalletBase will not get sent over.

---

lib/src/screens/restore/wallet_restore_from_seed_form.dart
lib/src/widgets/seed_widget.dart

Fixes Seed Type selection when restoring a Monero wallet, (if you select legacy and go back and enter the page again, it will show polyseed, but with legacy fields, and when you tap on it, it will show that the selected is legacy, yet it's written polyseed)

misc-seed-page-fixes

---

android/app/build.gradle

This is a temporary workaround. Proper fix will involve not using `libtor.so` as an executable and using it as static library.
That fix will most likely occur when we will bring support for iOS.

fix: set `useLegacyPackaging = true` so `libtor.so` gets extracted

---

cw_core/lib/utils/proxy_socket/abstract.dart
cw_core/lib/utils/proxy_socket/insecure.dart
cw_core/lib/utils/proxy_socket/secure.dart
cw_core/lib/utils/proxy_socket/socks.dart

Should fix issues that were caused by ProxyWrapper abstract classes that added unnecessary async, which caused error leaks.

fix: make socket calls sync

---

cw_monero/lib/api/subaddress_list.dart
cw_monero/lib/monero_wallet.dart

monero wallets crashing when switching back from hardware wallet to another monero wallet

fix: monero wallets crashing when switching back from hardware wallet

---

lib/exchange/provider/chainflip_exchange_provider.dart

When we initially added Chainflip a quote only returned 1 response, this has changed over time to include 2 responses. We now take this into account an select the best option for the user (the one returning most money).

Migrate to new Chainflip endpoints

---

pubspec_base.yaml

Fixes build issue in current main
```
../../.pub-cache/hosted/pub.dev/polyseed-0.0.7/lib/src/mnemonics/legacy/legacy_seed_lang.dart:131:29: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
var checksum = crc32code(trimmedWords, Encoding.getByName('utf-8'));
^
../../.pub-cache/hosted/pub.dev/hashlib-1.22.0/lib/src/crc32.dart:52:5: Context: Found this candidate, but the arguments don't match.
int crc32code(
^^^^^^^^^
Target kernel_snapshot_program failed: Exception
```

fix: pin hashlib version

---

scripts/build_bitbox_flutter.sh

This fixes execution of the script on systems that have simple POSIX shell as /bin/sh (but still have bash installed)

fix: use bash for bitbox build script

---

res/values/strings_en.arb

> Fixes #2548 
I updated the English translation key 'exchange_trade_result_confirm' to capitalize 'Cake Wallet' and prevent edible-cake translations in other languages. The brand name should remain unlocalized in future translations.

i18n: fix brand capitalization in exchange confirmation
