cake-tech/cake_wallet

- analysis_options.yaml
- cw_monero/lib/subaddress_list.dart
CWA-154.
Removed hardcoded account index for getting of all subaddresses. Fixed exclude path for generated dart files for analyzer.
> Fixed getting of subaddresses for current selected account

- lib/src/screens/trade_details/track_trade_list_item.dart
- lib/src/screens/trade_details/trade_details_page.dart
- lib/view_model/trade_details_view_model.dart
Created new trade list item TrackTradeListItem to display and handle this information
> [cake-254] Added ability to track trade directly with a web browser for ChangeNow transactions

- res/values/strings_de.arb
- res/values/strings_en.arb
- res/values/strings_es.arb
- res/values/strings_hi.arb
- res/values/strings_hr.arb
- res/values/strings_it.arb
- res/values/strings_ja.arb
- res/values/strings_ko.arb
- res/values/strings_nl.arb
- res/values/strings_pl.arb
- res/values/strings_pt.arb
- res/values/strings_ru.arb
- res/values/strings_uk.arb
- res/values/strings_zh.arb
Text on welcome screen “Awesome wallet for Monero and Bitcoin” has been changed to “Awesome wallet for Monero, Bitcoin and Litecoin” .Updated first_wallet_text for all localization files.
> CW-1 Update localization for welcome screen

- LICENSE.md
- PRIVACY.md
- assets/text/Terms_of_Use.txt
Changes entity from Cake Technologies LLC to Cake Labs LLC and broadens language to cover monero.com and more coins. Changes have been reviewed by Vik and legal.
> Update Terms of Service. Minor updates for privacy policy and license

- lib/src/screens/send/send_template_page.dart
fix: keyboard jumping over fields in send template
> fix: keyboard jumping over fields in send template

- android/app/build.gradle
- ios/Podfile
- ios/Podfile.lock
upgrade unstoppable domain libraries for ios and Android to include support for polygon
> upgrade unstoppable dependencies to include support for polygon

- android/app/src/main/java/com/cakewallet/cake_wallet/MainActivity.java
- android/app/src/main/java/com/monero/app/MainActivity.java
- ios/CakeWallet/wakeLock.swift
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- lib/di.dart
- lib/entities/wake_lock.dart
- lib/reactions/on_wallet_sync_status_change.dart
Add native implementations for IOS and Android to keeping screen awake while synchronizing
> Cw 8 keep screen on while wallet synchronization

- res/values/strings_de.arb
- res/values/strings_en.arb
- res/values/strings_es.arb
- res/values/strings_hi.arb
- res/values/strings_hr.arb
- res/values/strings_it.arb
- res/values/strings_ja.arb
- res/values/strings_ko.arb
- res/values/strings_nl.arb
- res/values/strings_pl.arb
- res/values/strings_pt.arb
- res/values/strings_ru.arb
- res/values/strings_uk.arb
- res/values/strings_zh.arb
-Changed alert header text for XMR and BTC wallets to "Adress Detected"
-Updated all localization files
> Changed alert header text for XMR and BTC wallets

- lib/entities/wake_lock.dart
- Bug fix
- Change enableWakeScreen call return type from String to bool
-  Change disableWakeScreen call return type from String to bool
> change type string to bool in Wakelock class

- lib/src/screens/send/send_page.dart
- lib/view_model/send/send_view_model.dart
filter templates by current wallet type
> filter templates by current wallet type

- lib/src/screens/exchange/widgets/exchange_card.dart
moved currency picker button on the exchage screen to the left side
> Moved currency piker button to the left side

- lib/src/screens/exchange/widgets/exchange_card.dart
Changed divider color on the exchage screen for the dark mode.
> Fixed divider color

- lib/src/screens/receive/receive_page.dart
Set a theme-appropriate background for the list of subaddresses
> Cw 43 subaddress renaming visual bug

- lib/src/screens/dashboard/widgets/sync_indicator.dart
- lib/src/screens/dashboard/widgets/sync_indicator_icon.dart
- lib/src/screens/exchange/exchange_page.dart
- lib/src/screens/send/send_page.dart
sync status icon added on the Send and Exchange screens
> sync status icon added on the Send and Exchange screens

- lib/src/screens/receive/widgets/address_cell.dart
displays previously used addresses like first and last 8 characters of subaddress
> fixed subaddress label

- lib/src/screens/dashboard/dashboard_page.dart
- lib/src/screens/dashboard/widgets/sync_indicator.dart
Added routing to the Nodes Screen by clicking on the sync indicator.
> Added routing to the sync indicator

- lib/src/screens/monero_accounts/monero_account_list_page.dart
- lib/src/screens/monero_accounts/widgets/account_tile.dart
- lib/src/screens/receive/receive_page.dart
- lib/src/screens/receive/widgets/address_cell.dart
-added ability to rename currently selected account and subaddress
-fixed address cell background color
-fixed account title screen padding
> Cw 53 allow renaming of currently selected account and subaddress

- lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
Fixed qr image on Receive screen for Litecoin wallet
> Fixed qr image on Receive screen for Litecoin

- lib/src/screens/receive/receive_page.dart
> Updated receive screen

- lib/di.dart
- lib/view_model/send/send_view_model.dart
Hide available balance on the send screen for "hidden" mode
> Hidden mode for balance on send screen

- lib/src/screens/dashboard/widgets/action_button.dart
Increased tapping area on the dashbord buttons
> Increased tapping area on the dashbord buttons

- PRIVACY.md
Minor changes. Clarify definition of Node and broaden supported network language. Made it clearer we do not retain node information
> Update privacy policy

- PRIVACY.md
Break out into sections to make clearer what information we could receive from users and what we retain (if anything)
> Privacy policy

- lib/src/screens/contact/contact_list_page.dart
- lib/src/widgets/collapsible_standart_list.dart
- lib/src/widgets/standard_list.dart
Address book has been redesigned into a drop-down list
> Add collapse button to the address book

- lib/view_model/transaction_details_view_model.dart
Merge after new Monero.com site goes live
> Change Monero block explorer to Monero.com

- lib/haven/cw_haven.dart
Fixed display of Haven transaction info
> fix haven transaction info

- lib/core/address_validator.dart
Added validation of hvx,hvi,hvs Haven addresses
> added validation of hvx,hvi,hvs Haven addresses

- lib/entities/fio_address_provider.dart
- lib/entities/parse_address_from_domain.dart
- lib/entities/parsed_address.dart
- lib/src/screens/send/widgets/extract_address_from_parsed.dart
Added support for sending funds to FIO addresses for the selected asset.
> Added ability sending to FIO address

- lib/src/screens/restore/wallet_restore_from_keys_form.dart
- lib/src/screens/restore/wallet_restore_page.dart
Remove restore from date for haven restore form
> remove restore from date for haven restore form

- lib/src/screens/contact/contact_page.dart
Add paste option to address text field in new contact screen
> Add paste option to new contact screen

- lib/store/settings_store.dart
Save Haven current node after switching nodes
> Save Haven current node

- lib/di.dart
- lib/router.dart
- lib/src/screens/ionia/auth/ionia_welcome_page.dart
- lib/src/screens/ionia/cards/ionia_buy_card_detail_page.dart
- lib/src/screens/ionia/cards/ionia_buy_gift_card.dart
- lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
- lib/src/screens/ionia/widgets/card_item.dart
- lib/src/widgets/discount_badge.dart
- lib/view_model/ionia/ionia_view_model.dart
- res/values/strings_en.arb
> display virtual card

- lib/src/screens/wallet_keys/wallet_keys_page.dart
- lib/view_model/wallet_keys_view_model.dart
Remove WIF and Keys from BTC and LTC wallets in the Wallet seed/keys screen
> Hide keys for BTC & LTC

- lib/src/screens/ionia/auth/ionia_create_account_page.dart
- lib/src/screens/ionia/auth/ionia_login_page.dart
- lib/src/screens/ionia/auth/ionia_verify_otp_page.dart
- lib/src/screens/ionia/auth/ionia_welcome_page.dart
- lib/src/screens/ionia/cards/ionia_activate_debit_card_page.dart
- lib/src/screens/ionia/cards/ionia_buy_card_detail_page.dart
- lib/src/screens/ionia/cards/ionia_buy_gift_card.dart
- lib/src/screens/ionia/cards/ionia_debit_card_page.dart
- lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
- lib/src/screens/ionia/widgets/card_item.dart
- lib/src/widgets/cake_scrollbar.dart
- lib/src/widgets/discount_badge.dart
- lib/view_model/ionia/ionia_view_model.dart
- res/values/strings_en.arb
Update Ionia UI, remove filter icon
> Update UI with new fixes

- lib/src/screens/exchange/widgets/exchange_card.dart
> fix exchangenow payment request

- lib/src/screens/ionia/auth/ionia_create_account_page.dart
- lib/src/screens/ionia/auth/ionia_login_page.dart
- lib/src/screens/ionia/auth/ionia_verify_otp_page.dart
- lib/src/screens/ionia/auth/ionia_welcome_page.dart
- lib/src/screens/ionia/cards/ionia_account_page.dart
- lib/src/screens/ionia/cards/ionia_activate_debit_card_page.dart
- lib/src/screens/ionia/cards/ionia_buy_card_detail_page.dart
- lib/src/screens/ionia/cards/ionia_debit_card_page.dart
- lib/src/screens/ionia/cards/ionia_gift_card_detail_page.dart
- lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
Adjust font size for page headers
> Change ionia heading font style

- ios/Podfile.lock
- lib/src/screens/ionia/cards/ionia_buy_card_detail_page.dart
- lib/src/screens/ionia/cards/ionia_gift_card_detail_page.dart
fix currency format for card details and routing for mark as redeemed
> fix currency format for card details and routing for mark as redeemed

- PRIVACY.md
> Fix privacy policy spelling error

- lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
> fix search bar color

- lib/entities/emoji_string_extension.dart
fix triggered Yat alert for empty address string
> fix display of Yat alert when address is empty

- lib/src/screens/ionia/cards/ionia_gift_card_detail_page.dart
- lib/view_model/ionia/ionia_gift_card_details_view_model.dart
increase brightness for gift card detail page
> increase brightness for gift card detail page

- lib/view_model/ionia/ionia_gift_cards_list_view_model.dart
> sort Giftcards alphabetically

- cw_core/lib/crypto_currency.dart
AVAXC -> AVAX (C-CHAIN)
BTTBSC -> BTT (BSC)
USDTTRC20 -> USDT (TRX)
USDCSOL -> USDC (SOL)
> add tags and update  titles for currencies

- lib/exchange/simpleswap/simpleswap_exchange_provider.dart
Check for status code 201 instead of 200 as mentioned in SimpleSwap API documentation
> Fix SimpleSwap create exchange

- android/app/build.gradle
- android/build.gradle
- tool/configure.dart
- Update compile sdk version
- Update kotlin version
- Add missing `HavenAccountList` class to configure to be generated with `haven.dart` file
> Update android build configs

- android/app/build.gradle
Update compile SDK and add ndk version to run on mac
> Android Compile SDK and NDK update

- lib/src/screens/settings/widgets/settings_picker_cell.dart
- lib/src/widgets/picker.dart
- lib/src/widgets/standard_list.dart
- lib/view_model/buy/buy_amount_view_model.dart
- tool/configure.dart
- Fix late initialization exception when using late with Mobx [(ref)](https://github.com/mobxjs/mobx.dart/issues/598)
- Handle nullability of theme data
- Remove null checks from non-null variables
- Add checks on empty lists instead of it's nullability
> Cw 188 fix grey screen

- lib/src/widgets/primary_button.dart
> fix buttons UI

- lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
> fix CakePay icon

- lib/exchange/changenow/changenow_exchange_provider.dart
- lib/exchange/sideshift/sideshift_exchange_provider.dart
Allow null values from limits API in `ChangeNow` and `SideShift`
> Fix exchange limits issue

- lib/entities/default_settings_migration.dart
- lib/view_model/node_list/node_list_view_model.dart
Create haven default node instead of loading from YML cause they are throwing errors in parsing
**Edit**
fixed `.yml` files parsing in #543
> Fix Haven empty node list

- lib/src/widgets/base_alert_dialog.dart
> alerts UI fix

- lib/src/screens/exchange/widgets/present_provider_picker.dart
Fix exchange provider UI overflow
**Purpose:**
fixed splash color to be transparent as it was before flutter update, and fixed text-overflow
> Fix exchange provider style

- lib/entities/qr_scanner.dart
Used the new barcode_scan2 package instead
> Fix barcode scanner

- cw_monero/lib/api/transaction_history.dart
Add nullability to amount in transaction_history.dart
> Fix Send All error

- lib/src/screens/dashboard/widgets/address_page.dart
- lib/src/screens/receive/receive_page.dart
- lib/src/screens/seed/wallet_seed_page.dart
- pubspec_base.yaml
replaced shared plugin with share_plus plugin
> check share plugin usage

- lib/src/screens/buy/onramper_page.dart
It's not supported here, so removing to avoid confusion
> Remove Onramper swap

- lib/src/screens/exchange/widgets/currency_picker.dart
changed the text color of the search bar on the exchange currency picker
> currency picker UI bug

- lib/src/screens/settings/widgets/settings_link_provider_cell.dart
- lib/view_model/support_view_model.dart
- res/values/strings_de.arb
- res/values/strings_en.arb
- res/values/strings_es.arb
- res/values/strings_fr.arb
- res/values/strings_hi.arb
- res/values/strings_hr.arb
- res/values/strings_it.arb
- res/values/strings_ja.arb
- res/values/strings_ko.arb
- res/values/strings_nl.arb
- res/values/strings_pl.arb
- res/values/strings_pt.arb
- res/values/strings_ru.arb
- res/values/strings_uk.arb
- res/values/strings_zh.arb
Contacts of SideShift and SimpleSwap partners added to the Support section
> Add partners contacts

- cw_core/lib/monero_transaction_priority.dart
- cw_haven/lib/haven_wallet.dart
- cw_monero/lib/monero_wallet.dart
Changed Monero "regular" fee name to "automatic"
> change monero regular fee name to automatic

- assets/node_list.yml
- lib/entities/default_settings_migration.dart
- lib/main.dart
- lib/reactions/on_authentication_state_change.dart
- Check for Nodes if exists before adding them in nodes
- Fix nullability issue due to early access
- Fix Nodes_list,yml file structure
> CW-251-fix-duplicate-nodes

- cw_bitcoin/lib/bitcoin_transaction_priority.dart
- cw_core/lib/monero_transaction_priority.dart
- lib/entities/default_settings_migration.dart
- lib/main.dart
Validate bitcoin saved transaction priority due to some deprecated code in existing users app data
> Validate bitcoin saved transaction priority

- cw_bitcoin/lib/electrum.dart
> [CW-281] Lower target confirmation for medium

- android/app/src/main/AndroidManifestBase.xml
- lib/src/screens/root/root.dart
Navigate to send screen even if the user does not need to authenticate
> Fix Send screen not opening from URI

- .github/workflows/pr_test_build.yml
> Cw 261 enhance workflow

- lib/src/screens/settings/widgets/settings_picker_cell.dart
- lib/src/widgets/picker.dart
Fix Generic Type being enforced to extend Object
> Fix Settings Pickers Search

- cw_bitcoin/lib/electrum_wallet.dart
- lib/ionia/ionia_anypay.dart
add missing default priority for btc and ltc
> Fix Nullability issue in gift cards

- README.md
- Adds a list (for quick glance) of the current language files available for Cake.
- Added clarification around how to handle variables (denoted by a $ sign) within the .arb translation files.
> Changes to language file section of README.md

- .github/workflows/pr_test_build.yml
Add test variables to workflow for external PR support
> Add Test Variables to workflow

- lib/src/widgets/collapsible_standart_list.dart
fixed header color for Address book
> CW-222 fix header color

- scripts/android/build_haven.sh
- scripts/ios/build_haven.sh
https://github.com/haven-protocol-org/haven-main/compare/v3.0.0...v3.0.3
> Bump Haven to 3.0.3

- .github/workflows/cache_dependencies.yml
- .github/workflows/pr_test_build.yml
Github is deprecating Ubuntu 18.04, so I updated it to 20.04 and tested the build flow with and without cached data
> Update build environment

- scripts/android/build_haven.sh
- scripts/ios/build_haven.sh
https://github.com/haven-protocol-org/haven-main/compare/v3.0.3...v3.0.7
> Bump Haven to 3.0.7

- lib/view_model/send/send_view_model.dart
Issue Number (if Applicable): Fixes # N/A
Compare the scheme of the URI with the full name of the currency instead of the abbreviated one
> Qr scheme fix

- lib/di.dart
- lib/src/screens/subaddress/address_edit_or_create_page.dart
- lib/view_model/wallet_address_list/wallet_address_edit_or_create_view_model.dart
fix editing label subaddresses
> CW-296 fix editing label subaddresses

- lib/main.dart
Issue Number (if Applicable): Fixes #N/A
Prevent multiple UI errors from showing multiple alerts
> Prevent multiple Error dialogs at once

- lib/di.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_wallet_selection_dropdown.dart
- lib/src/widgets/nav_bar.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
Issue Number (if Applicable): Fixes #N/A
Add Wallet selection dropdown to dashboard desktop view
> Desktop AppBar

- lib/main.dart
- lib/utils/exception_handler.dart
Issue Number (if Applicable): Fixes #N/A
- Avoid reporting user errors
- Enhance code readability regarding exception handling
> Avoid reporting user errors

- lib/core/address_validator.dart
Add LTC to twitter address parsing
> Add LTC to twitter address parsing

- lib/view_model/support_view_model.dart
> Fix support URLs

- lib/src/screens/pin_code/pin_code_widget.dart
- lib/src/widgets/nav_bar.dart
- Listen to keyboard events on PIN screen
- Fix PIN buttons style
> Allow Keyboard usage on PIN screen

- lib/router.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_dashboard_actions.dart
- lib/src/widgets/market_place_item.dart
Add Marketplace to the dashboard
> Add Marketplace to dashboard view

- lib/src/screens/new_wallet/new_wallet_page.dart
- lib/src/screens/new_wallet/new_wallet_type_page.dart
- lib/src/screens/pin_code/pin_code_widget.dart
- lib/utils/responsive_layout_util.dart
> [CW-310] Add constraints to images on macos

- lib/di.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/src/screens/dashboard/desktop_dashboard_page.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_sidebar/side_menu.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_sidebar/side_menu_item.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
- lib/src/screens/settings/desktop_settings/dashboard_settings_page.dart
- lib/view_model/dashboard/desktop_sidebar_view_model.dart
> MacOS settings icon to be a toggle

- lib/src/screens/ionia/auth/ionia_create_account_page.dart
- lib/src/screens/ionia/auth/ionia_login_page.dart
- lib/src/screens/ionia/auth/ionia_verify_otp_page.dart
- lib/src/widgets/base_text_form_field.dart
Add onFieldSubmitted to allow "enter" button interaction
> Add keyboard control for desktop

- lib/router.dart
- lib/src/screens/exchange/exchange_template_page.dart
- lib/src/screens/exchange/widgets/currency_picker.dart
- lib/src/screens/exchange/widgets/desktop_exchange_cards_section.dart
- lib/src/screens/exchange/widgets/exchange_card.dart
- lib/src/screens/send/send_page.dart
- lib/src/widgets/address_text_field.dart
- lib/src/widgets/alert_close_button.dart
- lib/src/widgets/base_text_form_field.dart
- lib/src/widgets/check_box_picker.dart
- lib/src/widgets/picker.dart
- lib/utils/responsive_layout_util.dart
> Fix Popup width constraint and add focus orders

- lib/src/screens/base_page.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_dashboard_navbar.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
- lib/src/screens/restore/restore_from_backup_page.dart
- lib/src/screens/restore/restore_options_page.dart
- lib/src/screens/seed/pre_seed_page.dart
- lib/src/screens/seed/wallet_seed_page.dart
- lib/src/widgets/desktop_nav_bar.dart
- lib/src/widgets/nav_bar.dart
> Fix alignment in create and restore wallet screens

- lib/src/screens/dashboard/desktop_dashboard_page.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
- lib/src/screens/exchange/widgets/exchange_card.dart
- lib/src/screens/ionia/cards/ionia_buy_gift_card.dart
- lib/src/widgets/address_text_field.dart
> Fix desktop background color and address book view issues

- lib/src/screens/backup/backup_page.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/utils/exception_handler.dart
- lib/utils/share_util.dart
Add share files to share utils and unify the fix for ipad
> Fix Share issue on iPad

- lib/src/screens/settings/widgets/settings_link_provider_cell.dart
- lib/view_model/support_view_model.dart
Fix support links/emails not opening
> Fix Support links

- lib/exchange/trocador/trocador_exchange_provider.dart
> Fix payout and input address swap trocador

- lib/src/widgets/address_text_field.dart
> CW-246-Disable-autocorrect-in-Send-address-field-and-make-keyboard-incognito

- lib/entities/parse_address_from_domain.dart
https://unstoppabledomains.com/blog/categories/announcements/article/unstoppable-domains-and-polygon-labs-launch-.polygon
Issue Number (if Applicable): Fixes N/A
> Add `.polygon` to unstoppable domains

- assets/node_list.yml
Has been down for 3 months
https://nodes.monero.com/incident/94
@OmarHatem28 do we need to handle any migrations for users?
Issue Number (if Applicable): Fixes N/A
> Remove supportxmr node

- cw_core/pubspec.lock
- cw_haven/pubspec.lock
- cw_monero/pubspec.lock
- ios/Podfile.lock
- lib/entities/default_settings_migration.dart
- lib/reactions/bootstrap.dart
- lib/utils/exception_handler.dart
- lib/utils/share_util.dart
> V4.6.0 reports fixes

- lib/di.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_wallet_selection_dropdown.dart
- lib/view_model/node_list/node_list_view_model.dart
- lib/view_model/wallet_keys_view_model.dart
> CW-324 Refresh current settings page if wallet changed

- lib/di.dart
- lib/reactions/on_authentication_state_change.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/src/screens/dashboard/desktop_dashboard_page.dart
- lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
- lib/utils/exception_handler.dart
- macos/Runner.xcodeproj/project.pbxproj
Remove navigation workaround for duplicate key, and fix the issue by handling creation/disposing of global key
> Fix Create Wallet Seeds screen issue

- lib/src/screens/settings/security_backup_page.dart
> Require pin code on backup and seed/view page

- lib/view_model/exchange/exchange_view_model.dart
> CW-340-Truncate-estimated-btc-amount-in-Exchange

- .github/workflows/pr_test_build.yml
- lib/core/fiat_conversion_service.dart
- tool/utils/secret_key.dart
> Add `fiatApiKey`

- cw_bitcoin/lib/bitcoin_transaction_wrong_balance_exception.dart
- cw_haven/lib/haven_wallet.dart
- cw_monero/lib/monero_wallet.dart
Ideally these should be moved to the translation strings
> Improve sending error messages

- lib/src/screens/exchange/exchange_template_page.dart
- lib/src/screens/receive/anonpay_invoice_page.dart
> Add padding to adjust top

- android/app/src/main/java/com/cakewallet/cake_wallet/MainActivity.java
- ios/Runner/AppDelegate.swift
> CW-347-Hide-app-screenshot-from-app-switcher

- pubspec_base.yaml
Fixate device info package version
> Fix PR workflow issue

- lib/view_model/exchange/exchange_trade_view_model.dart
> CW-350-add-click-to-copy-for-the-exchange-amount-in-the-invoice

- lib/src/screens/base_page.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/src/screens/new_wallet/new_wallet_page.dart
- lib/src/screens/pin_code/pin_code_widget.dart
- lib/src/screens/receive/receive_page.dart
- lib/src/screens/receive/widgets/address_cell.dart
- lib/src/screens/settings/connection_sync_page.dart
- lib/src/widgets/introducing_card.dart
Issue Number (if Applicable): Fixes #536 Fixes #564
> Cw 304 enhance talkback

- lib/src/widgets/check_box_picker.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec_base.yaml
- Fix Exchange picker UI issue
> Pre-release bug fixes

- cw_core/lib/crypto_currency.dart
- lib/core/address_validator.dart
- lib/exchange/sideshift/sideshift_exchange_provider.dart
- lib/exchange/trocador/trocador_exchange_provider.dart
Issue Number (if Applicable): Fixes N/A
> Add btcln; add 2 assets to SideShift

- lib/exchange/exchange_template.dart
- lib/src/screens/exchange/exchange_page.dart
- lib/src/screens/exchange/exchange_template_page.dart
- lib/store/templates/exchange_template_store.dart
- lib/view_model/exchange/exchange_view_model.dart
> CW-359-Exchange-Template-not-saving-currency-tag

- lib/src/screens/base_page.dart
- lib/src/screens/dashboard/widgets/address_page.dart
- lib/src/screens/receive/receive_page.dart
- lib/src/screens/wallet_list/wallet_list_page.dart
> Cw 363 back button on receive screen in bright theme is white

- lib/src/screens/send/widgets/send_card.dart
> Fix keyboard is not entering text in fields until focus

- lib/src/screens/dashboard/widgets/filter_widget.dart
- lib/src/widgets/check_box_picker.dart
- lib/src/widgets/modal_widget.dart
- lib/src/widgets/picker.dart
- lib/src/widgets/picker_wrapper_widget.dart
> CW-376-picker-ui-issue

- lib/src/screens/anonpay_details/anonpay_details_page.dart
Added cancellation of Anonpay updateInvoice timer on AnonpayDetailsPage
> CW-379-Investigate-trade-ID-status-updates

- pubspec_base.yaml
- scripts/android/build_monero.sh
- scripts/ios/build_monero.sh
- scripts/macos/build_monero.sh
> Update Monero package

- lib/src/screens/wallet_unlock/wallet_unlock_page.dart
> Add theme refactor to linux branch

- .github/workflows/pr_test_build.yml
- lib/exchange/sideshift/sideshift_exchange_provider.dart
- lib/view_model/exchange/exchange_trade_view_model.dart
- lib/view_model/exchange/exchange_view_model.dart
- tool/utils/secret_key.dart
> CW-411 Update sideshift api

- lib/buy/onramper/onramper_buy_provider.dart
Logic can be better handled by IP
> Remove defaultFiat

- build-guide-linux.md
- lib/src/screens/dashboard/desktop_widgets/desktop_action_button.dart
Issue Number (if Applicable): Fixes #981 #983
Linux Build's Dashboard Buttons now turn cursor into Pointer (Click) Symbol on Hover.
Done by simple wrapping of Button's Padding with a `MouseRegion` widget that transform the cursor.
> Button: Cursor to Pointer on Hover

- lib/exchange/changenow/changenow_exchange_provider.dart
- lib/utils/distribution_info.dart
- lib/view_model/exchange/exchange_trade_view_model.dart
- lib/view_model/exchange/exchange_view_model.dart
- lib/view_model/trade_details_view_model.dart
added payloads fields to ChangeNOW request
> CW-424-ChangeNOW-add-payload-details

- lib/view_model/exchange/exchange_view_model.dart
> CW-65 Add "all" button LTC exchange screen

- lib/src/screens/dashboard/widgets/balance_page.dart
- lib/src/screens/dashboard/widgets/market_place_page.dart
- lib/utils/feature_flag.dart
> Disable Cake Pay Mobile

- cw_monero/lib/monero_wallet.dart
- lib/core/wallet_loading_service.dart
- lib/di.dart
- lib/src/screens/wallet/wallet_edit_page.dart
- lib/src/screens/wallet_list/wallet_list_page.dart
- lib/src/screens/wallet_unlock/wallet_unlock_arguments.dart
- lib/src/screens/wallet_unlock/wallet_unlock_page.dart
- lib/view_model/wallet_list/wallet_edit_view_model.dart
- lib/view_model/wallet_unlock_loadable_view_model.dart
- lib/view_model/wallet_unlock_verifiable_view_model.dart
- lib/view_model/wallet_unlock_view_model.dart
> Linux: fixes for wallet rename

- cw_monero/lib/monero_wallet.dart
- lib/core/wallet_loading_service.dart
> add monero rename related fixes into main

- .github/workflows/pr_test_build.yml
- lib/utils/exception_handler.dart
> Free Up GitHub Actions Ubuntu Runner Disk Space

- android/app/build.gradle
- lib/src/screens/backup/backup_page.dart
- lib/src/screens/seed/pre_seed_page.dart
- lib/src/screens/seed/wallet_seed_page.dart
- lib/src/screens/setup_2fa/setup_2fa_qr_page.dart
- lib/src/screens/wallet_keys/wallet_keys_page.dart
- lib/utils/clipboard_util.dart
- pubspec_base.yaml
Use Android 13 SensitiveClipboard for sensitive Stings
> CW-423 Use SensitiveClipboard for sensitive Stings

- lib/src/screens/nodes/node_create_or_edit_page.dart
- lib/src/screens/nodes/widgets/node_form.dart
- lib/view_model/node_list/node_create_or_edit_view_model.dart
> feat: Introduce QR Scanning to add new node

- android/app/src/main/AndroidManifestBase.xml
- scripts/android/inject_app_details.sh
Add version code and version name to android configuration
> CW-450 Add version code & version name to android configs

- .github/workflows/pr_test_build.yml
- cw_core/lib/erc20_token.dart
- cw_ethereum/lib/ethereum_wallet.dart
- lib/view_model/exchange/exchange_trade_view_model.dart
- lib/view_model/restore/restore_from_qr_vm.dart
- Enable ethereum auto send in exchange
- Add Eth Restore from QR option
> Enable Eth/Erc20 auto send in exchange

- lib/entities/main_actions.dart
- lib/src/screens/dashboard/dashboard_page.dart
> feat: Replace buy action to use onramper

- PRIVACY.md
Minor changes, including:
* Better reference Fiat API service and the ability to turn it off
* Better reference optional Error logs sending
* Minor other clarifications
> Minor changes: Update privacy policy [skip ci]

- lib/entities/parse_address_from_domain.dart
> Update UD domains

- README.md
> Add Ethereum and f-droid to readme

- README.md
Fix my major omission :grimacing:
skip ci
> Readme: update to include desktop

- lib/anonpay/anonpay_api.dart
- lib/src/screens/receive/anonpay_invoice_page.dart
> Fix Ethereum network for anonpay invoice

- lib/view_model/set_up_2fa_viewmodel.dart
> fix: Rotate TOTP Secret

- .github/workflows/cache_dependencies.yml
- cw_monero/lib/monero_wallet_service.dart
- cw_monero/macos/Classes/monero_api.cpp
- lib/entities/default_settings_migration.dart
- macos/Podfile.lock
- Recover from wallet loading exceptions (basic_string & input_stream)
- Recover from removed cached wallets
> Fix Wallet Loading issues (basic_string & input_stream)

- .github/workflows/cache_dependencies.yml
- scripts/android/build_haven.sh
Allow triggering cache workflow manually
Fix haven build script
> Generic fixes

- .github/workflows/pr_test_build.yml
- cw_core/pubspec.lock
- scripts/android/build_haven.sh
> feat: Replace transfer.sh

- cw_monero/lib/monero_wallet_addresses.dart
Address should not be empty when Auto generate subaddresses is disabled
> CW-481 Fix empty Address

- cw_monero/ios/Classes/monero_api.cpp
- lib/core/fiat_conversion_service.dart
- lib/core/wallet_change_listener_view_model.dart
- lib/di.dart
- lib/view_model/exchange/exchange_view_model.dart
- lib/view_model/send/send_view_model.dart
- lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
> Fiat api fix

- cw_core/lib/transaction_info.dart
- cw_ethereum/lib/ethereum_transaction_info.dart
- cw_ethereum/lib/ethereum_wallet.dart
- cw_ethereum/lib/pending_ethereum_transaction.dart
- lib/exchange/sideshift/sideshift_exchange_provider.dart
- lib/view_model/transaction_details_view_model.dart
> CW- 463 Fix transaction receive address not showing for Eth/Erc20

- android/app/build.gradle
- android/build.gradle
- cw_core/lib/root_dir.dart
- cw_haven/android/build.gradle
- cw_haven/lib/haven_wallet.dart
- cw_monero/android/build.gradle
- cw_monero/ios/Classes/monero_api.cpp
- cw_shared_external/android/build.gradle
- lib/entities/default_settings_migration.dart
- lib/ionia/ionia_service.dart
- pubspec_base.yaml
> Cw linux direct input password build changes

- lib/src/screens/receive/anonpay_receive_page.dart
- lib/src/screens/receive/widgets/qr_widget.dart
- lib/src/screens/wallet_keys/wallet_keys_page.dart
- lib/utils/brightness_util.dart
Add Brightness Util to check for platform before increasing brightness
> Fix Desktop QR issue

- cw_monero/lib/monero_wallet.dart
Don't throw a coin-control-error if all Inputs are selected.
> CW-489 Skip Warning if all monero utxo are selected

- android/app/src/main/AndroidManifestBase.xml
- android/app/src/main/res/drawable-night/launch_background.xml
> CW-478-Startup-splash-screen-is-white-in-all-themes.-Change-to-black-in-dark-themes

- lib/core/wallet_connect/wallet_connect_key_service.dart
- lib/di.dart
- lib/src/screens/settings/connection_sync_page.dart
> fix: Wallet type check when registering key service

- res/values/strings_fr.arb
> fix in strings_fr.arb

- res/values/strings_pl.arb
> Update of strings_pl.arb

- cw_nano/lib/nano_wallet.dart
> fix , bug and swapping for nano

- lib/src/screens/dashboard/widgets/address_page.dart
- lib/src/screens/dashboard/widgets/header_row.dart
- lib/src/screens/dashboard/widgets/present_receive_option_picker.dart
- lib/src/screens/exchange/widgets/exchange_card.dart
- lib/src/widgets/alert_close_button.dart
Issue Number (if Applicable): Fixes #1061 
Accessibility fixes:
- share address button
- address book button
- close button
- copy address button
- transaction filter button
> CW-479-Accessibility-fixes

- lib/core/backup_service.dart
> disable bio auth for macos

- res/values/strings_fr.arb
> Updated FR translations

- lib/core/backup_service.dart
disables bio auth on desktop when importing from a backup
also enforces dark theme when importing from a backup on desktop
> disable bio auth

- lib/core/auth_service.dart
- lib/entities/encrypt.dart
- pubspec_base.yaml
> Secure storage overwrite fix

- lib/src/screens/restore/wallet_restore_page.dart
Added 'advanced privacy settings' button on the 'Restore from Seed' screen.
> CW-524-Add-Advanced-privacy-settings-screen-to-restore-from-seed-flow-as-well

- res/values/strings_fr.arb
> Minor fixes to FR localization

- cw_bitcoin_cash/lib/src/bitcoin_cash_address_utils.dart
- cw_bitcoin_cash/lib/src/bitcoin_cash_wallet.dart
- lib/buy/robinhood/robinhood_buy_provider.dart
- lib/entities/main_actions.dart
Add BCH Support to Robinhood and handle Robinhood Exceptions more gracefully
> Cw 523 robinhood enhancements

- cw_nano/lib/nano_wallet.dart
> fix nano being sent to only the first output address in list

- lib/view_model/dashboard/nft_view_model.dart
Lookup NFTs only if the current wallet is an Ethereum Wallet
> Lookup NFTs only if the current wallet is an Ethereum Wallet

- cw_monero/lib/monero_wallet_service.dart
Fix refresh from 0 on creating polyseeds
> Fix refresh from 0 on creating polyseeds

- cw_monero/lib/api/wallet_manager.dart
- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/monero_wallet_service.dart
Remove polyseed seed workaround and fix properly by just storing the wallet
> Remove polyseed seed workaround and fix missing seed

- .github/workflows/pr_test_build.yml
> allow manual builds on any branch

- lib/src/screens/dashboard/dashboard_page.dart
Issue Number (if Applicable): Fixes #1223 
> fix dot indicator color

- lib/src/screens/settings/display_settings_page.dart
- lib/src/screens/settings/widgets/settings_theme_choice.dart
- lib/src/widgets/standard_switch.dart
> CW-536-Many-unlabeled-buttons-issue-1201

- lib/core/wallet_connect/evm_chain_service.dart
- lib/core/wallet_connect/wallet_connect_key_service.dart
- lib/core/wallet_connect/web3wallet_service.dart
- lib/di.dart
- lib/entities/load_current_wallet.dart
- lib/store/app_store.dart
- lib/view_model/wallet_creation_vm.dart
- lib/view_model/wallet_list/wallet_list_view_model.dart
> fix: Fix walletconnect connecting only with the first wallet

- cw_core/lib/erc20_token.dart
- cw_ethereum/lib/ethereum_wallet.dart
> CW-545-Overriding-Erc20-tokens-list

- android/app/build.gradle
- android/app/src/main/AndroidManifestBase.xml
- cw_bitcoin/lib/electrum_balance.dart
- lib/entities/fiat_currency.dart
- lib/src/screens/buy/buy_webview_page.dart
- lib/src/screens/buy/webview_page.dart
- lib/src/screens/dashboard/pages/transactions_page.dart
- lib/src/screens/support_chat/widgets/chatwoot_widget.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec_base.yaml
> Cw 553 update inappwebview

- lib/buy/dfx/dfx_buy_provider.dart
- lib/entities/provider_types.dart
> Enable DFX for polygon wallet

- lib/src/screens/new_wallet/new_wallet_type_page.dart
- res/values/strings_ar.arb
- res/values/strings_bg.arb
- res/values/strings_cs.arb
- res/values/strings_de.arb
- res/values/strings_en.arb
- res/values/strings_es.arb
- res/values/strings_fr.arb
- res/values/strings_ha.arb
- res/values/strings_hi.arb
- res/values/strings_hr.arb
- res/values/strings_id.arb
- res/values/strings_it.arb
- res/values/strings_ja.arb
- res/values/strings_ko.arb
- res/values/strings_my.arb
- res/values/strings_nl.arb
- res/values/strings_pl.arb
- res/values/strings_pt.arb
- res/values/strings_ru.arb
- res/values/strings_th.arb
- res/values/strings_tl.arb
- res/values/strings_tr.arb
- res/values/strings_uk.arb
- res/values/strings_ur.arb
- res/values/strings_yo.arb
- res/values/strings_zh.arb
> CW-480-Remove-Ability-To-Create-Haven-Wallets

- lib/core/auth_service.dart
- lib/core/backup_service.dart
- lib/di.dart
- lib/entities/default_settings_migration.dart
- lib/entities/preferences_key.dart
- lib/entities/secret_store_key.dart
- lib/main.dart
- lib/src/screens/root/root.dart
- lib/store/settings_store.dart
- lib/view_model/settings/security_settings_view_model.dart
- lib/view_model/wallet_list/wallet_list_view_model.dart
> Cw 540 encrypt shared

- lib/src/screens/exchange_trade/exchange_trade_page.dart
- macos/Podfile.lock
> CW-569-Route-to-dashboard-when-exchange-is-done

- lib/store/settings_store.dart
- lib/view_model/set_up_2fa_viewmodel.dart
Issue Number (if Applicable): Fixes #1242 
Fixes bug that allows 2FA to be bypassed.
> CW-566-Cake2FA-Bypass-Bug

- .github/workflows/pr_test_build.yml
- configure_cake_wallet.sh
> Add missing packages pub get, to model generator [skip ci]

- cw_bitcoin/lib/bitcoin_address_record.dart
- cw_bitcoin/lib/electrum_wallet_addresses.dart
- lib/bitcoin/cw_bitcoin.dart
- lib/src/screens/receive/widgets/qr_widget.dart
> fix generate new electrum address

- lib/palette.dart
> Fix colors

- macos/Podfile
> build fix for mac os when building on mac os sonoma

- lib/core/address_validator.dart
- lib/entities/parse_address_from_domain.dart
- lib/entities/parsed_address.dart
- lib/mastodon/mastodon_user.dart
- lib/src/screens/send/widgets/extract_address_from_parsed.dart
- lib/src/widgets/alert_with_one_action.dart
- lib/src/widgets/base_alert_dialog.dart
- lib/twitter/twitter_api.dart
- lib/twitter/twitter_user.dart
> Cw 586 display user twitter image in birdpay

- cw_solana/lib/solana_client.dart
> fix: Solana message improvement

- tool/configure.dart
Fix pubspec generation on windows
> Fix pubspec generation on windows

- lib/entities/default_settings_migration.dart
- lib/main.dart
> disable service status api if fiat api is disabled

- lib/entities/default_settings_migration.dart
> update migration behavior slightly

- lib/buy/moonpay/moonpay_provider.dart
> fix moonpay amount being locked on the buy page

- lib/src/screens/dashboard/dashboard_page.dart
- lib/view_model/dashboard/dashboard_view_model.dart
Implemented a pull-to-refresh feature to manually reconnect wallets on the dashboard page.
> Pull-to-Refresh to reconnect wallets

- configure_cake_wallet.sh
- run-android.sh
> script updates and new run-android script

- .github/workflows/pr_test_build.yml
- android/build.gradle
- cw_bitcoin/pubspec.yaml
- cw_bitcoin_cash/pubspec.yaml
- cw_core/pubspec.yaml
- cw_ethereum/pubspec.yaml
- cw_evm/pubspec.yaml
- cw_haven/pubspec.yaml
- cw_monero/pubspec.yaml
- cw_nano/pubspec.yaml
- cw_polygon/pubspec.yaml
- cw_solana/pubspec.yaml
- lib/entities/biometric_auth.dart
- lib/locales/hausa_intl.dart
- lib/locales/yoruba_intl.dart
- lib/src/screens/settings/security_backup_page.dart
- lib/src/screens/settings/tor_page.dart
- lib/src/widgets/validable_annotated_editable_text.dart
- lib/view_model/auth_view_model.dart
- pubspec_base.yaml
- pubspec_description.yaml
Reverts cake-tech/cake_wallet#1367
> Revert "version bump to 3.13.9, auth working on mac"

- cw_solana/lib/solana_wallet.dart
> CW-619: Harmonize Solana wallet keys across various apps

- lib/bitcoin/cw_bitcoin.dart
- lib/src/screens/send/widgets/send_card.dart
- lib/src/screens/settings/other_settings_page.dart
- lib/src/screens/settings/widgets/setting_priority_picker_cell.dart
- lib/src/screens/transaction_details/rbf_details_list_fee_picker_item.dart
- lib/src/screens/transaction_details/rbf_details_page.dart
- lib/src/widgets/picker.dart
- lib/src/widgets/standard_picker_list.dart
- lib/view_model/send/send_view_model.dart
- lib/view_model/settings/other_settings_view_model.dart
- lib/view_model/transaction_details_view_model.dart
- tool/configure.dart
> dynamic max fee rate value

- cw_bitcoin/lib/electrum_wallet.dart
Fixed displayed balance Issue for Address List
> CW-623-addresses-in-the-previous-address-list-are-showing-incorrect-balance

- cw_bitcoin/lib/electrum_wallet.dart
- cw_bitcoin/lib/exceptions.dart
- cw_bitcoin/lib/pending_bitcoin_transaction.dart
- cw_bitcoin/pubspec.lock
- cw_bitcoin_cash/lib/src/pending_bitcoin_cash_transaction.dart
- cw_core/lib/exceptions.dart
- cw_core/lib/unspent_transaction_output.dart
- lib/src/screens/send/send_page.dart
- lib/view_model/send/send_view_model.dart
> Enhance bitcoin error message

- cw_bitcoin/lib/electrum_derivations.dart
- lib/bitcoin/cw_bitcoin.dart
- lib/nano/cw_nano.dart
- lib/view_model/wallet_creation_vm.dart
- lib/view_model/wallet_restore_view_model.dart
- tool/configure.dart
> Bip39 minor enhancements

- lib/di.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/utils/alert_scheduler.dart
- lib/view_model/auto_backup_view_model.dart
- lib/view_model/dashboard/dashboard_view_model.dart
> auto backup branch with mac auth branch merged in

- run-android.sh
> minor script fix

- cw_core/lib/wallet_info.dart
- lib/src/screens/root/root.dart
> Generic Enhancements

- lib/nano/cw_nano.dart
> nano derivation fix

- assets/tron_node_list.yml
- cw_tron/lib/tron_client.dart
- lib/view_model/send/send_view_model.dart
> Tron-Wallet-Fixes

- cw_core/lib/window_size.dart
- lib/main.dart
- lib/src/screens/dashboard/desktop_widgets/dropdown_item_widget.dart
- lib/src/screens/settings/desktop_settings/desktop_settings_page.dart
- lib/src/screens/wallet_list/wallet_list_page.dart
- macos/Runner/AppDelegate.swift
> Desktop-Enhancements

- lib/entities/parse_address_from_domain.dart
- lib/entities/parsed_address.dart
- lib/exchange/provider/thorchain_exchange.provider.dart
- lib/src/screens/exchange/exchange_page.dart
- lib/src/screens/send/widgets/extract_address_from_parsed.dart
- lib/view_model/send/output.dart
> thor name to address lookup

- pubspec_base.yaml
> update flutter secure storage

- cw_tron/lib/tron_client.dart
> fix: Modify tron fee to eliminate spike due to first tx

- cw_bitcoin/lib/bitcoin_wallet.dart
- cw_bitcoin/lib/electrum_wallet.dart
- cw_bitcoin/lib/electrum_wallet_snapshot.dart
- lib/bitcoin/cw_bitcoin.dart
- lib/view_model/wallet_creation_vm.dart
- tool/configure.dart
> [wip] fixing

- cw_tron/lib/tron_client.dart
- macos/Podfile.lock
- scripts/android/pubspec_gen.sh
- scripts/ios/app_config.sh
- scripts/macos/app_config.sh
> fix: Tron Timeout Issue

- lib/di.dart
- lib/src/screens/connect_device/connect_device_page.dart
> Maybe Fix Bluetooth Popup

- lib/src/screens/contact/contact_page.dart
> Fix Contact page reaction excuted more than once

- cw_monero/ios/Classes/monero_api.cpp
- cw_monero/lib/api/signatures.dart
- cw_monero/lib/api/types.dart
- cw_monero/lib/api/wallet.dart
Store Wallet on creation, just to be safe
> Potential fix for missing polyseeds in the future

- lib/src/screens/base_page.dart
- lib/src/screens/exchange/exchange_page.dart
- lib/src/screens/ionia/cards/ionia_gift_card_detail_page.dart
- lib/src/screens/new_wallet/new_wallet_page.dart
- lib/src/screens/new_wallet/new_wallet_type_page.dart
- lib/src/screens/restore/restore_from_backup_page.dart
- lib/src/screens/restore/wallet_restore_page.dart
- lib/src/screens/send/send_page.dart
- lib/src/screens/send/send_template_page.dart
- lib/utils/route_aware.dart
Implemented automatic unfocus on the current text field across various screens (Exchange, Send, Address Book, QR, Paste, etc.) to prevent the keyboard from popping up.
> CW-636-1-Unfocus text fields when push to next one

- cw_core/lib/transaction_info.dart
- cw_ethereum/lib/ethereum_client.dart
- cw_ethereum/lib/ethereum_transaction_info.dart
- cw_ethereum/lib/ethereum_wallet.dart
- cw_evm/lib/evm_chain_transaction_info.dart
- cw_evm/lib/evm_chain_transaction_model.dart
- cw_evm/lib/evm_chain_wallet.dart
- lib/ethereum/cw_ethereum.dart
- lib/polygon/cw_polygon.dart
- lib/src/screens/dashboard/pages/transactions_page.dart
- lib/view_model/contact_list/contact_list_view_model.dart
- lib/view_model/dashboard/home_settings_view_model.dart
- tool/configure.dart
Removed ERC20 token transactions when disabled.
Hidden ETH transactions using "transfer" and "deposit" signature methods.
Fixed display of wallet contacts in address book.
> Erc20 token transactions are displaying incorrectly

- lib/entities/parse_address_from_domain.dart
> oa1 ticker needs to be lowercase

- cw_monero/lib/api/transaction_history.dart
- cw_monero/lib/api/wallet_manager.dart
- cw_wownero/lib/api/transaction_history.dart
- cw_wownero/lib/api/wallet_manager.dart
- lib/src/screens/send/widgets/send_card.dart
- lib/view_model/send/output.dart
> fix: fiat amount when sending all

- pubspec_base.yaml
Add support for Ledger Stax devices
> support ledger stax

- cw_core/lib/transaction_info.dart
- cw_monero/lib/api/wallet_manager.dart
- cw_monero/lib/monero_subaddress_list.dart
- cw_monero/lib/monero_transaction_info.dart
- cw_wownero/lib/api/wallet_manager.dart
- cw_wownero/lib/wownero_transaction_info.dart
- lib/view_model/transaction_details_view_model.dart
- scripts/prepare_moneroc.sh
Bumped the commit because wownero is unreachable for quite some time, and I really don't want to spend any more time copying already cloned repositories when wownero git is offline.
> update monero_c to fix unreachable wownero git hosting

- lib/exchange/provider/sideshift_exchange_provider.dart
- lib/view_model/exchange/exchange_view_model.dart
> CW-674: Improve Exchange Flow With Timeout For Rates

- lib/di.dart
- lib/src/screens/receive/receive_page.dart
- lib/view_model/dashboard/balance_view_model.dart
- lib/view_model/dashboard/dashboard_view_model.dart
- lib/view_model/monero_account_list/monero_account_edit_or_create_view_model.dart
- lib/view_model/monero_account_list/monero_account_list_view_model.dart
- lib/view_model/node_list/node_create_or_edit_view_model.dart
- lib/view_model/wallet_address_list/wallet_address_edit_or_create_view_model.dart
- lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
> CW-681 Add address and account list to Wownero

- cw_monero/lib/api/wallet_manager.dart
- cw_wownero/lib/api/wallet_manager.dart
- scripts/prepare_moneroc.sh
make "Null check used on null value" errors when .so errors out more …
bump monero_c commit to fix enotes error
> Small fixes

- cw_monero/lib/api/wallet_manager.dart
- cw_wownero/lib/api/wallet_manager.dart
- lib/view_model/wallet_keys_view_model.dart
> fix invalid wallet pointer getting set even when we throw

- .github/workflows/pr_test_build.yml
- pubspec_base.yaml
> CW-680: Fix Wakelock Issue

- assets/litecoin_electrum_server_list.yml
- cw_core/lib/wallet_service.dart
- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/monero_wallet_service.dart
- lib/core/wallet_loading_service.dart
- lib/di.dart
- lib/reactions/on_authentication_state_change.dart
- lib/src/screens/monero_accounts/monero_account_edit_or_create_page.dart
- lib/utils/exception_handler.dart
> Try to show seeds if wallet files gets corrupted

- lib/src/screens/dashboard/pages/balance_page.dart
- lib/view_model/dashboard/dashboard_view_model.dart
Just a simple error on the main page that shows when something went terribly wrong.
> add card for when monero wallet is in broken state

- cw_bitcoin/pubspec.yaml
- cw_evm/pubspec.yaml
- pubspec_base.yaml
Add Support for the new Ledger Flex device
> Add Ledger Flex Support

- cw_bitcoin/lib/electrum.dart
> Request timeout fix

- lib/bitcoin/cw_bitcoin.dart
- lib/src/screens/transaction_details/rbf_details_list_fee_picker_item.dart
- lib/src/widgets/standard_picker_list.dart
- lib/view_model/transaction_details_view_model.dart
- tool/configure.dart
> fix custom rate issue

- lib/di.dart
- lib/src/screens/settings/other_settings_page.dart
- lib/src/screens/transaction_details/transaction_details_page.dart
- lib/src/widgets/picker.dart
- lib/view_model/settings/other_settings_view_model.dart
> fix zero initial fee rates in RBF rate picker

- lib/app_scroll_behavior.dart
- lib/main.dart
- lib/src/screens/dashboard/dashboard_page.dart
- lib/src/screens/dashboard/pages/balance_page.dart
- lib/src/screens/restore/wallet_restore_page.dart
- lib/src/screens/send/send_page.dart
- lib/src/screens/send/send_template_page.dart
> Cw 567 cant swipe through menus on desktop builds

- README.md
Use proper markdown image format for logo on README.md
Fixes https://github.com/cake-tech/cake_wallet/issues/1590
> Fix logo sizing

- lib/src/screens/new_wallet/new_wallet_page.dart
- lib/src/screens/restore/wallet_restore_page.dart
- pubspec_base.yaml
> add mutex around _confirmForm to prevent the wallets from breaking

- ios/Runner/AppDelegate.swift
> Fix: Remove resolution scope from unstoppable domains plugin

- cw_bitcoin/lib/utils.dart
> fix: p2sh addr

- cw_bitcoin/lib/electrum_wallet.dart
> more info on privkey error

- scripts/macos/build_monero_all.sh
> fix macos universal build

- lib/src/screens/dashboard/desktop_widgets/desktop_wallet_selection_dropdown.dart
- lib/store/settings_store.dart
> Windows fix

- cw_bitcoin/lib/electrum_wallet.dart
> bitcoin-cash fix missing required parameter

- cw_bitcoin/lib/electrum.dart
- cw_bitcoin/lib/electrum_wallet.dart
- cw_core/lib/wallet_base.dart
- lib/bitcoin/cw_bitcoin.dart
- lib/view_model/node_list/node_list_view_model.dart
- lib/view_model/transaction_details_view_model.dart
> Fix testnet

- .github/workflows/cache_dependencies.yml
- .github/workflows/pr_test_build_android.yml
Updated and switched the distribution, previous one showed cloudflare error to our runner
> update setup-java and switch distribution

- res/values/strings_es.arb
Fix a Spanish string.
Small fix. I don't know how to compile in Linux.
> Fix Spanish string

- windows/CMakeLists.txt
Removes deprecated monero_c dependencies
> Fix windows build

- lib/src/screens/restore/wallet_restore_page.dart
- lib/view_model/restore/restore_from_qr_vm.dart
- lib/view_model/wallet_creation_vm.dart
> allow restoring electrum seeds

- lib/view_model/dashboard/transaction_list_item.dart
This will show the count of confirmations for outgoing transactions
> show pending status for outgoing transactions

- lib/src/widgets/check_box_picker.dart
> fix disabling exchange providers

- cw_nano/lib/nano_client.dart
- cw_nano/lib/nano_wallet_service.dart
- lib/nano/cw_nano.dart
- lib/src/screens/nano/nano_change_rep_page.dart
- lib/view_model/wallet_restore_view_model.dart
> Nano rep page + derivation fixes

- lib/main.dart
- lib/view_model/restore_from_backup_view_model.dart
> CW-695: Fix Zone Mismatch Error Triggered By Restoring Backup

- assets/node_list.yml
- lib/entities/default_settings_migration.dart
- lib/main.dart
Removes node.moneroworld.com from default nodes
> Remove node.moneroworld.com

- cw_bitcoin/lib/electrum.dart
- cw_bitcoin/lib/electrum_wallet.dart
> quick fix for the reconnection issue

- cw_bitcoin/lib/electrum_wallet.dart
> quick fix for UTXOs updating issue

- cw_bitcoin/pubspec.lock
- cw_bitcoin/pubspec.yaml
- cw_core/pubspec.lock
- cw_core/pubspec.yaml
- cw_haven/pubspec.lock
- cw_monero/pubspec.lock
- cw_wownero/pubspec.lock
> Sp scanner dep

- cw_monero/lib/api/wallet_manager.dart
- cw_wownero/lib/api/wallet_manager.dart
Check Jira for details
To testers - test restore from keys, especially non deterministic ones.
> do not restore deterministic wallet if it's not one

- cw_bitcoin/lib/electrum_transaction_history.dart
- cw_bitcoin/lib/electrum_wallet.dart
> CW-719 Transaction dates shows incorrectly

- lib/src/screens/dashboard/widgets/menu_widget.dart
> Fix list UI having double width on some parts

- lib/exchange/provider/stealth_ex_exchange_provider.dart
Reverts cake-tech/cake_wallet#1697
> Revert "normalize-polygon-for-StealthEX"

- cw_core/lib/crypto_currency.dart
- lib/exchange/provider/letsexchange_exchange_provider.dart
> Change tags to POL

- cw_bitcoin/lib/electrum_wallet.dart
> CW-694 Used Addresses balance issue

- cw_bitcoin/lib/exceptions.dart
> fix min fee not met exception

- cw_bitcoin_cash/lib/src/bitcoin_cash_wallet.dart
- cw_bitcoin_cash/lib/src/bitcoin_cash_wallet_service.dart
- cw_ethereum/lib/ethereum_wallet.dart
- cw_ethereum/lib/ethereum_wallet_service.dart
- cw_evm/lib/evm_chain_wallet.dart
- cw_evm/lib/evm_chain_wallet_creation_credentials.dart
- cw_nano/lib/nano_wallet.dart
- cw_nano/lib/nano_wallet_creation_credentials.dart
- cw_polygon/lib/polygon_wallet.dart
- cw_polygon/lib/polygon_wallet_service.dart
- cw_solana/lib/solana_wallet.dart
- cw_solana/lib/solana_wallet_creation_credentials.dart
- cw_tron/lib/tron_wallet.dart
- cw_tron/lib/tron_wallet_creation_credentials.dart
- cw_tron/lib/tron_wallet_service.dart
- lib/entities/unstoppable_domain_address.dart
- lib/ethereum/cw_ethereum.dart
- lib/nano/cw_nano.dart
- lib/polygon/cw_polygon.dart
- lib/solana/cw_solana.dart
- lib/src/screens/new_wallet/advanced_privacy_settings_page.dart
- lib/src/screens/restore/wallet_restore_from_seed_form.dart
- lib/src/screens/restore/wallet_restore_page.dart
- lib/tron/cw_tron.dart
- lib/view_model/advanced_privacy_settings_view_model.dart
- lib/view_model/restore/restore_from_qr_vm.dart
- lib/view_model/wallet_new_vm.dart
- lib/view_model/wallet_restore_view_model.dart
- tool/configure.dart
> Add passphrase support for Eth, Polygon, and Tron

- lib/core/backup_service.dart
- lib/di.dart
- lib/entities/transaction_description.dart
- lib/src/screens/transaction_details/widgets/textfield_list_row.dart
- lib/src/screens/unspent_coins/unspent_coins_details_page.dart
> Cw 769 fix transaction notes not showing

- lib/core/backup_service.dart
This should ensure that files are flushed to disk before this function returns.
Also, replaced foreach loop with for loop.
How to test? Restore backup multiple times, if it didn't fail then it's good
> Set flush: true in backup service

- cw_bitcoin/lib/electrum_wallet.dart
> feat: add onError exception

- lib/entities/default_settings_migration.dart
> fix: Issue with nownodes on older wallets

- lib/core/address_validator.dart
> fix P2wpkhAddress btc ltc validation

- lib/core/backup_service.dart
> Fix issues when restoring wallets from backup

- lib/entities/default_settings_migration.dart
- lib/view_model/send/send_view_model.dart
> Disable sendAll on native EVM Currencies

- cw_core/lib/wallet_addresses.dart
- cw_evm/lib/evm_chain_wallet_addresses.dart
- cw_monero/lib/monero_wallet_addresses.dart
- cw_nano/lib/nano_wallet_addresses.dart
- cw_solana/lib/solana_wallet_addresses.dart
- cw_tron/lib/tron_wallet_addresses.dart
- cw_wownero/lib/wownero_wallet_addresses.dart
- lib/view_model/send/send_view_model.dart
- lib/view_model/transaction_details_view_model.dart
> transaction description key id address

- assets/bitcoin_electrum_server_list.yml
- lib/entities/default_settings_migration.dart
- lib/main.dart
> enable ssl for btc-electrum

- cw_bitcoin/lib/electrum_wallet_addresses.dart
> fix MobX Exception: computed values issue

- lib/store/dashboard/transaction_filter_store.dart
- lib/view_model/dashboard/dashboard_view_model.dart
Issue Number (if Applicable): Fixes #1778
> fix: sp filter option

- lib/view_model/send/send_view_model.dart
> CW-806-send-screen-minor-enhancement

- PRIVACY.md
- README.md
- SECURITY.md
- build-guide-linux.md
Hello
I fixed several spelling issues.
Br, Elias.
> Docs spelling issues

- cw_bitcoin/lib/electrum_wallet.dart
- cw_bitcoin/pubspec.lock
> Electrum enhancements

- lib/cake_pay/cake_pay_order.dart
- lib/cake_pay/cake_pay_service.dart
- lib/src/screens/cake_pay/cards/cake_pay_confirm_purchase_card_page.dart
> fix: paymentUrls is null

- lib/buy/onramper/onramper_buy_provider.dart
> fix-onramper-default-crypto

- lib/view_model/send/send_view_model.dart
> fix the UI issue with sending outputs

- lib/entities/parse_address_from_domain.dart
> add xmr to unstoppable domain

- cw_monero/lib/ledger.dart
- cw_monero/lib/monero_wallet_service.dart
- lib/monero/cw_monero.dart
- lib/view_model/hardware_wallet/ledger_view_model.dart
- tool/configure.dart
> Better Ledger Connection handling

- lib/src/screens/contact/contact_list_page.dart
- lib/view_model/contact_list/contact_list_view_model.dart
> fix the UI issue with address book

- lib/exchange/provider/trocador_exchange_provider.dart
Move the api key of trocador to the headers
> Secure Trocador key

- cw_monero/lib/api/transaction_history.dart
> CW-834-investigate-the-empty-error-popup-when-sending-monero

- cw_monero/lib/api/transaction_history.dart
- cw_monero/lib/api/wallet.dart
- cw_monero/lib/pending_monero_transaction.dart
This will show the error instead so don't merge it yet (merge after testing when I remove that)
> CW-826 Fix missing tx keys in monero

- lib/buy/onramper/onramper_buy_provider.dart
- lib/src/screens/buy/buy_sell_page.dart
- lib/view_model/buy/buy_sell_view_model.dart
> fix onramper network tag plus UI

- lib/buy/robinhood/robinhood_buy_provider.dart
- lib/view_model/buy/buy_sell_view_model.dart
> prevent calling unsupported payment method

- lib/exchange/provider/letsexchange_exchange_provider.dart
> fix infinity values in LetsExchange fixed rate

- res/values/strings_pt.arb
Portuguese translation fix of nanogpt_subtitle string
> NanoGPT portuguese string fix

- cw_bitcoin/lib/electrum_transaction_history.dart
- cw_evm/lib/evm_chain_transaction_history.dart
- cw_nano/lib/nano_transaction_history.dart
- cw_solana/lib/solana_transaction_history.dart
- cw_tron/lib/tron_transaction_history.dart
> CW-855 Transactions History Bug

- lib/core/address_validator.dart
> add legacy BCH address format

- lib/di.dart
- lib/router.dart
- lib/routes.dart
- lib/src/screens/send/send_page.dart
- lib/src/screens/send/transaction_success_info_page.dart
> CW-863-Give-proper-transaction-sent-feedback

- cw_bitcoin/lib/litecoin_wallet.dart
> fix pending LtC transaction

- lib/src/screens/connect_device/connect_device_page.dart
- lib/view_model/hardware_wallet/ledger_view_model.dart
This PR addresses some edge cases of an already listened-to stream and uncanceled timer.
> More Ledger Monero Fixes

- cw_core/lib/node.dart
- lib/src/screens/seed/seed_verification/seed_verification_step_view.dart
> support Adding query params to node url

- lib/core/wallet_loading_service.dart
- lib/entities/default_settings_migration.dart
- lib/entities/evm_transaction_error_fees_handler.dart
- lib/main.dart
- lib/src/screens/wallet_connect/utils/string_parsing.dart
- lib/utils/exception_handler.dart
- lib/view_model/dashboard/dashboard_view_model.dart
> Switch to SSL for Cake's Electrum and Monero nodes

- lib/src/screens/seed/seed_verification/seed_verification_step_view.dart
> fix: Generic fixes

- .github/workflows/automated_integration_test.yml
- .github/workflows/pr_test_build_android.yml
- .github/workflows/pr_test_build_linux.yml
- assets/solana_node_list.yml
- cw_core/lib/exceptions.dart
- cw_solana/lib/solana_client.dart
- cw_solana/lib/solana_exceptions.dart
- cw_solana/pubspec.yaml
- lib/core/wallet_connect/web3wallet_service.dart
- lib/entities/default_settings_migration.dart
- lib/view_model/send/send_view_model.dart
- pubspec_base.yaml
- tool/utils/secret_key.dart
> change Solana node

- lib/cake_pay/cake_pay_api.dart
- lib/cake_pay/cake_pay_card.dart
- lib/cake_pay/cake_pay_service.dart
- lib/cake_pay/cake_pay_vendor.dart
> fix: wrong card for vendor country

- cw_bitcoin/lib/electrum_wallet.dart
- lib/src/screens/seed/seed_verification/seed_verification_page.dart
- lib/utils/feature_flag.dart
- lib/view_model/wallet_seed_view_model.dart
Add safe refresh for unspent coins before creating a transaction
> Fix electrum unspent coins error

- cw_solana/lib/solana_client.dart
> fix creating associated token account

- cw_evm/lib/evm_chain_wallet.dart
> Fix fee check for erc20 transactions

- linux/my_application.cc
> Rename linux app

- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/monero_wallet_service.dart
> Fix unavailable balance not refreshing after the app got opened

- cw_bitcoin/lib/electrum_wallet_addresses.dart
> Fix Mobx issue

- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/monero_wallet_service.dart
Reverts cake-tech/cake_wallet#1920
> Revert "Fix unavailable balance not refreshing after the app got opened"

- lib/bitcoin/cw_bitcoin.dart
- lib/view_model/exchange/exchange_view_model.dart
- lib/view_model/send/send_view_model.dart
- tool/configure.dart
> Disable mweb coins for exchanges

- cw_solana/lib/solana_client.dart
> Fix Sending SPL token issue

- cw_monero/lib/monero_wallet.dart
- lib/view_model/dashboard/dashboard_view_model.dart
> Monero balance tx display issue

- lib/src/screens/dashboard/pages/balance/balance_row_widget.dart
- lib/view_model/dashboard/balance_view_model.dart
> Balance card fixes

- lib/entities/default_settings_migration.dart
> fix print in default_settings_migration

- build-guide-linux.md
- build-guide-win.md
fix some typos for build-guide-*.md
> chore: fix some typos for build-guide-*.md

- pubspec_base.yaml
https://github.com/cake-tech/cake_wallet/actions/runs/12789294702/job/35652407078 <- fixes this error. Actual fix for the issue will come in CW-910
> Pin ledger_flutter_plus dependency to fix builds

- lib/core/backup_service.dart
- lib/entities/parse_address_from_domain.dart
- lib/entities/parsed_address.dart
- lib/entities/preferences_key.dart
- lib/entities/wellknown_record.dart
- lib/src/screens/send/widgets/extract_address_from_parsed.dart
- lib/src/screens/settings/domain_lookups_page.dart
- lib/store/settings_store.dart
- lib/view_model/settings/privacy_settings_view_model.dart
> .well-known domain support

- lib/di.dart
- lib/store/app_store.dart
- lib/view_model/dashboard/dashboard_view_model.dart
This PR should fix issues caused by the transactions in the dashboard view model not being cleared properly.
> CW-855-Transactions-not-cleared-correctly-when-switching-wallets

- lib/src/screens/wallet_keys/wallet_keys_page.dart
> Add copy icon to block height display

- lib/view_model/wallet_keys_view_model.dart
> Fix monero.com build by removing cw_wownero import

- scripts/functions.sh
- scripts/ios/build_monero_all.sh
- scripts/macos/build_monero_all.sh
> fix MAKE_JOB_COUNT on darwin, and use it on ios and macos scripts

- cw_core/lib/exceptions.dart
- cw_zano/lib/zano_wallet_exceptions.dart
- lib/src/screens/restore/wallet_restore_page.dart
- lib/view_model/wallet_creation_vm.dart
- Fix error popup showing multiple times
- Improve/generalize error handling
> Improve Error Handling

- cw_monero/pubspec.lock
- cw_monero/pubspec.yaml
- cw_wownero/pubspec.lock
- cw_wownero/pubspec.yaml
- cw_zano/pubspec.lock
- cw_zano/pubspec.yaml
- scripts/prepare_moneroc.sh
> CW-887 Update error message for failed to get earliest fork height

- .github/workflows/automated_integration_test.yml
- .github/workflows/pr_test_build_android.yml
- .github/workflows/pr_test_build_linux.yml
- lib/entities/default_settings_migration.dart
- lib/exchange/exchange_provider_description.dart
- lib/exchange/provider/quantex_exchange_provider.dart
- lib/exchange/provider/swaptrade_exchange_provider.dart
- lib/view_model/exchange/exchange_trade_view_model.dart
- lib/view_model/exchange/exchange_view_model.dart
- lib/view_model/support_view_model.dart
- lib/view_model/trade_details_view_model.dart
- tool/utils/secret_key.dart
> Change Quantex to SwapTrade

- lib/src/screens/settings/desktop_settings/desktop_settings_page.dart
- lib/src/screens/wallet_list/wallet_list_page.dart
- lib/src/widgets/setting_actions.dart
> Keep drawer opened

- cw_monero/lib/api/wallet.dart
- cw_monero/lib/api/wallet_manager.dart
- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/monero_wallet_service.dart
- cw_wownero/lib/api/wallet.dart
- cw_wownero/lib/api/wallet_manager.dart
- cw_wownero/lib/wownero_wallet.dart
- cw_wownero/lib/wownero_wallet_service.dart
- lib/monero/cw_monero.dart
- lib/src/screens/wallet_keys/wallet_keys_page.dart
- lib/view_model/advanced_privacy_settings_view_model.dart
- lib/view_model/wallet_keys_view_model.dart
- lib/view_model/wallet_new_vm.dart
- lib/wownero/cw_wownero.dart
- tool/configure.dart
> CW-711 passphrase for XMR/WOWcreation

- lib/src/screens/wallet_keys/wallet_keys_page.dart
- lib/view_model/wallet_keys_view_model.dart
- lib/zano/cw_zano.dart
- tool/configure.dart
> show Zano keys properly in the keys tab

- lib/entities/qr_scanner.dart
- lib/src/screens/ur/animated_ur_page.dart
- lib/src/widgets/address_text_field.dart
- lib/view_model/node_list/node_create_or_edit_view_model.dart
- lib/view_model/restore/wallet_restore_from_qr_code.dart
> fix null check when user exits out of qr code scanner

- cw_monero/pubspec.lock
- cw_monero/pubspec.yaml
- cw_wownero/pubspec.lock
- cw_wownero/pubspec.yaml
- cw_zano/pubspec.lock
- cw_zano/pubspec.yaml
- scripts/prepare_moneroc.sh
Fixes the issue affecting lower end devices
> fix cn_slow_hash on devices with limited stack

- lib/entities/fiat_currency.dart
> CW-814-Add-Armenian-AMD-Currency

- cw_monero/lib/api/wallet_manager.dart
> Use different error message for invalid seed restore

- lib/src/screens/dashboard/pages/balance/balance_row_widget.dart
- lib/src/widgets/dashboard_card_widget.dart
- lib/src/widgets/setting_actions.dart
- Fixes a color bug with  the dashboard card widget
- Adds back wallets menu button
- TBD
> Ux enhancements

- lib/exchange/provider/letsexchange_exchange_provider.dart
- lib/exchange/provider/stealth_ex_exchange_provider.dart
> Fix Dates in Transaction history

- lib/exchange/provider/trocador_exchange_provider.dart
> Migrate trocador api

- cw_monero/pubspec.lock
- cw_monero/pubspec.yaml
- cw_wownero/pubspec.lock
- cw_wownero/pubspec.yaml
- cw_zano/pubspec.lock
- cw_zano/pubspec.yaml
- scripts/prepare_moneroc.sh
> fix x64 monero_c android dependencies

- cw_monero/pubspec.lock
- cw_monero/pubspec.yaml
- cw_wownero/pubspec.lock
- cw_wownero/pubspec.yaml
- cw_zano/lib/api/model/create_wallet_result.dart
- cw_zano/lib/api/model/wi_extended.dart
- cw_zano/lib/zano_wallet.dart
- cw_zano/lib/zano_wallet_api.dart
- cw_zano/lib/zano_wallet_service.dart
- cw_zano/pubspec.lock
- cw_zano/pubspec.yaml
- lib/src/screens/new_wallet/advanced_privacy_settings_page.dart
- lib/src/screens/wallet_keys/wallet_keys_page.dart
- lib/view_model/advanced_privacy_settings_view_model.dart
- lib/view_model/wallet_new_vm.dart
- lib/zano/cw_zano.dart
- scripts/prepare_moneroc.sh
- tool/configure.dart
> CW-934 Implement passphrase creation for zano

- cw_core/lib/zano_asset.dart
> Zano asset logo

- .github/workflows/pr_test_build_android.yml
> drop slack suffix on ci builds

- lib/src/screens/pin_code/pin_code_widget.dart
Update PIN page sizing and colors
> Update PIN page

- lib/di.dart
- lib/src/screens/support_chat/support_chat_page.dart
- lib/src/screens/support_chat/widgets/chatwoot_widget.dart
- lib/view_model/support_view_model.dart
This PR allows us to add additional attributes to the in-app support chat to allow the support team to swiftly resolve any issues.
> Add app-version to Chatwoot Contact Attributes

- lib/src/screens/send/widgets/send_card.dart
> fix fiat amount on token change

- lib/buy/dfx/dfx_buy_provider.dart
Hey Cake friends
We are changing our subdomain from services. to app.
The update is not urgent, but it makes sense to make this change. Services. will continue to be offered in the future but we should switch to app. as default. 
Do not hesitate to contact me if you have any questions.
> Update dfx subdomain

- lib/core/address_validator.dart
- lib/src/screens/send/send_page.dart
> CW-924-Don't-prompt-to-save-to-address-book-on-standard-Bitcoin-Litecoin-Bitcoin-Cash-addresses

- cw_bitcoin/lib/electrum_wallet.dart
Fix edge case of sending amount that will leave near dust amount as a…
> Fix edge case for BTC/LTC sending near dust amount

- lib/buy/moonpay/moonpay_provider.dart
> Fixate decimal points to 2

- cw_decred/lib/api/libdcrwallet.dart
- cw_decred/lib/wallet.dart
- lib/view_model/send/output.dart
- lib/view_model/send/send_view_model.dart
Also fix tx time and the fee shown on pending transactions.
> decred: Fix contact save inquiry.

- cw_bitcoin/lib/litecoin_wallet.dart
> Fix LTC not saving passphrase

- lib/core/backup_service.dart
> dont export/import pinlength

- .github/workflows/pr_test_build_android.yml
- .github/workflows/pr_test_build_linux.yml
- Dockerfile
> add missing android-35 dependency to Dockerfile

- docs/builds/ANDROID.md
- docs/builds/IOS.md
- docs/builds/MACOS.md
> add decred to docs

- cw_decred/lib/api/libdcrwallet.dart
- cw_decred/lib/wallet.dart
- cw_decred/lib/wallet_service.dart
- scripts/android/build_decred.sh
- scripts/ios/build_decred.sh
- scripts/macos/build_decred.sh
> Reduce decred wallet size

- lib/src/widgets/bottom_sheet/confirm_sending_bottom_sheet_widget.dart
- lib/src/widgets/standard_slide_button_widget.dart
> fix-colors-for-address-tile-send-UI

- .github/workflows/no_print_in_dart.yaml
- cw_core/lib/utils/print_verbose.dart
- tool/append_translation.dart
- tool/download_moneroc_prebuilds.dart
- tool/generate_localization.dart
- tool/print_verbose_dummy.dart
- tool/translation_add_lang.dart
- tool/translation_consistence.dart
- tool/utils/translation/arb_file_utils.dart
This reduces log amount when stacktrace is missing on release build.
> send logs about trace only in debug mode

- scripts/android/build_decred.sh
- scripts/ios/build_decred.sh
/bin/sh is not always /bin/bash.
> fix syntax errors in decred script

- cw_monero/lib/api/transaction_history.dart
- cw_monero/lib/monero_wallet.dart
> CW-1019 properly await multDest transaction so it won't freeze the UI

- lib/src/screens/new_wallet/wallet_group_description_page.dart
- lib/src/screens/new_wallet/wallet_group_existing_seed_description_page.dart
- lib/src/screens/send/send_page.dart
- lib/src/widgets/bottom_sheet/confirm_sending_bottom_sheet_widget.dart
- lib/src/widgets/bottom_sheet/info_bottom_sheet_widget.dart
> Cw 1018 minor UI enhancements

- lib/core/backup_service_v3.dart
- lib/view_model/restore_from_backup_view_model.dart
> Better handle backup errors

- lib/src/widgets/adaptable_page_view.dart
> fix-null-check-operator-issue-for-multiple-recipients-transaction

- cw_monero/lib/api/wallet.dart
> set seed language if seed_language is in error message

- lib/view_model/send/output.dart
> Fix fiat-based sending on Decred and Nano wallets

- lib/exchange/provider/xoswap_exchange_provider.dart
- lib/src/screens/exchange_trade/exchange_confirm_page.dart
> CW-1028-Fix-XOSwap-pair-id

- .github/workflows/automated_integration_test.yml
- .github/workflows/no_print_in_dart.yaml
- .github/workflows/no_restricted_imports.yaml
https://github.com/actions/runner-images/issues/11101
> ci: updade runner from 20.04 to 24.04

- lib/exchange/provider/simpleswap_exchange_provider.dart
- lib/view_model/exchange/exchange_view_model.dart
> Disable SimpleSwap from the Swap flow

- lib/src/screens/exchange_trade/exchange_trade_external_send_page.dart
- lib/src/screens/exchange_trade/exchange_trade_page.dart
> fix: Background color for swap screen and external send details screen looking wierd across themes

- lib/src/screens/send/send_page.dart
- lib/view_model/send/send_view_model.dart
This PR adopts the new bottom-sheet based flow for Ledger
> Adopt bottom-sheet send flow for ledger

- lib/buy/onramper/onramper_buy_provider.dart
> Update OnRamper params

- lib/router.dart
- lib/src/screens/connect_device/connect_device_page.dart
- lib/src/screens/wallet_list/wallet_list_page.dart
Show correct title when reconnecting yo your ledger
> Show correct title when reconnecting to your ledger device

- lib/src/screens/send/send_page.dart
> CW-1031-Fix-gray-send-bottom-sheet

- cw_decred/lib/wallet.dart
- cw_monero/lib/monero_unspent.dart
- cw_monero/lib/monero_wallet.dart
- lib/src/screens/send/widgets/send_card.dart
- lib/view_model/send/send_view_model.dart
- lib/view_model/unspent_coins/unspent_coins_list_view_model.dart
fix: monero frozen coins, call updateSendingBalance, display "ALL" balance properly
> fix: incorrect balance reporting

- cw_core/lib/unspent_transaction_output.dart
- lib/view_model/unspent_coins/unspent_coins_list_view_model.dart
> fix: incorrect balance in send card

- cw_core/lib/erc20_token.dart
- cw_ethereum/lib/ethereum_wallet.dart
- cw_evm/lib/evm_chain_wallet.dart
- cw_polygon/lib/polygon_wallet.dart
- lib/src/screens/send/send_page.dart
Label existing scam tokens because users can get scammed twice ¯\_(ツ)_/¯
> Label existing scam tokens

- lib/src/screens/dashboard/pages/address_page.dart
> AnonPay-integration-nonfunctional-in-Monero-com

- lib/src/screens/dashboard/widgets/action_button.dart
| TextOverflow.clip.png | TextOverflow.ellipsis.png | TextOverflow.fade.png | TextOverflow.visible.png |
| --- | --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/80aa7fb7-c1f2-460e-92c7-f80abd6b2430) | ![image](https://github.com/user-attachments/assets/a2ce60b2-fd31-4dfa-a52a-bf6bad67cb49) | ![image](https://github.com/user-attachments/assets/81150eca-9401-4c6b-aa1a-ad5d8da09473) | ![image](https://github.com/user-attachments/assets/1e149aa3-b447-4499-b0b3-0e1b41140ad1) |
I've went with TextOverflow.visible.
> ui: maxLines: 1 on bottom menu

- lib/src/screens/send/send_page.dart
> potential-fix-bottom-sheet-navigation-context-issue

- assets/node_list.yml
- lib/buy/onramper/onramper_buy_provider.dart
> Cw 1032 verify on ramper integration

- android/app/build.gradle
- android/app/proguard-rules.pro
> remove shrinkResources and minifyEnabled to reduce apk size

- lib/buy/robinhood/robinhood_buy_provider.dart
> CW-1039-Verify-Robinhood-integration

- lib/core/open_crypto_pay/open_cryptopay_service.dart
Fixes amount mapping for different cased Tickers in OCP
> fix amount mapping for OCP

- cw_core/lib/wallet_type.dart
- lib/src/screens/contact/contact_list_page.dart
- lib/src/widgets/alert_with_two_actions.dart
- lib/src/widgets/base_alert_dialog.dart
- lib/utils/address_formatter.dart
> Address-formatting-enhancements-MWEB

- lib/entities/wallet_manager.dart
- lib/view_model/wallet_list/wallet_list_view_model.dart
Confirmed by @tuxpizza to be a fix for disappearing wallets.
> CW-821: fix: wallet grouping eating wallets

- cw_solana/lib/solana_wallet.dart
> Solana New Fixes

- lib/exchange/trade_state.dart
- lib/src/screens/exchange_trade/exchange_trade_page.dart
> CW-988-Stuck-at-Sending-screen-when-swap

- .github/pull_request_template.md
- lib/src/screens/dashboard/widgets/filter_widget.dart
- lib/src/widgets/alert_close_button.dart
> Cw 1038 filter transaction popup not scrollable

- lib/view_model/restore_from_backup_view_model.dart
> fix: more verbose errors in backups

- lib/di.dart
- lib/haven/cw_haven.dart
> Add the code to enable removing Haven wallets

- lib/core/backup_service.dart
- lib/di.dart
- lib/router.dart
- lib/routes.dart
- lib/src/screens/dev/secure_preferences_page.dart
- lib/src/screens/settings/other_settings_page.dart
- lib/view_model/dev/secure_preferences.dart
Adds screen that can be used to recover wallet password
> feat(dev): add secrets dev screen (used to recover corrupted wallet)

- cw_bitcoin/lib/bitcoin_address_record.dart
- cw_bitcoin/lib/electrum_wallet_addresses.dart
- cw_monero/lib/monero_wallet_addresses.dart
> Cw 925 improve automatic subaddress generation behavior

- lib/view_model/contact_list/contact_view_model.dart
> CW-950-Editing-Contacts-issue

- cw_decred/lib/wallet.dart
- cw_decred/lib/wallet_service.dart
- cw_monero/lib/api/account_list.dart
- cw_monero/lib/api/coins_info.dart
- cw_monero/lib/api/subaddress_list.dart
- cw_monero/lib/api/transaction_history.dart
- cw_monero/lib/api/wallet.dart
- cw_monero/lib/api/wallet_manager.dart
- cw_monero/lib/ledger.dart
- cw_monero/lib/monero_account_list.dart
- cw_monero/lib/monero_unspent.dart
- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/monero_wallet_service.dart
- cw_monero/pubspec.lock
- cw_monero/pubspec.yaml
- cw_wownero/pubspec.lock
- cw_wownero/pubspec.yaml
- cw_zano/pubspec.lock
- cw_zano/pubspec.yaml
- ios/Podfile.lock
- lib/core/wallet_loading_service.dart
- lib/monero/cw_monero.dart
- lib/view_model/dashboard/dashboard_view_model.dart
- lib/view_model/send/send_view_model.dart
- scripts/prepare_moneroc.sh
> fix(cw_monero): prevent monero wallet from breaking during rename

- lib/src/screens/exchange_trade/exchange_trade_page.dart
> context-null-check-issue-in-exchange-trade

- lib/buy/onramper/onramper_buy_provider.dart
> onramper-fetch-payment-types-exception

- lib/di.dart
- lib/view_model/monero_account_list/monero_account_list_view_model.dart
> Amount-are-showed-in-hide-balance-mode-when-changing-account

- cw_tron/lib/tron_client.dart
- cw_zano/lib/api/model/destination.dart
- lib/core/node_address_validator.dart
> chore: fix some typos in comment

- lib/src/screens/restore/restore_options_page.dart
> CW-1065: Disable Camera Action In Wallet Restore for Desktop

- lib/src/screens/trade_details/trade_details_page.dart
- lib/src/widgets/list_row.dart
> CW-799: Allow Tap to Copy on Exchange URL

- cw_monero/lib/api/wallet.dart
- lib/view_model/send/send_view_model.dart
fix: catch error in newly added fetchTransactions call
fix: null handling in cw_monero
> fix: null handling and fetchTransactions

- cw_monero/lib/api/wallet.dart
- cw_monero/lib/monero_wallet.dart
- cw_monero/lib/pending_monero_transaction.dart
- lib/view_model/send/send_view_model.dart
> fix(cw_monero): transaction not appearing after send

- cw_monero/lib/pending_monero_transaction.dart
> fix(cw_monero): wait a bit before refreshing txlist so it appears

- cw_ethereum/lib/ethereum_client.dart
- cw_polygon/lib/polygon_client.dart
- lib/view_model/dashboard/home_settings_view_model.dart
> CW-1057: Migrate to EtherScan v2 API for supported EVM chains

- cw_monero/lib/api/transaction_history.dart
- cw_monero/lib/pending_monero_transaction.dart
> fix(cw_monero): properly await transaction commit

- lib/router.dart
- lib/src/widgets/base_text_form_field.dart
- lib/themes/core/theme_store.dart
… the themeMode is system mode
> Modify Themes Startup Behaviour

- lib/main.dart
- lib/src/screens/root/root.dart
- lib/themes/core/theme_store.dart
> Update Theme Setup

- lib/core/backup_service.dart
- lib/core/backup_service_v3.dart
This PR adds a sanity check to assure wallet types are restored correctly
> CW-1092-restoring-from-backup-doesnt-maintain-hardware-wallets

- lib/src/screens/welcome/welcome_page.dart
- lib/src/widgets/cake_image_widget.dart
> CW-1087: New Themes Flow Overview

- cw_evm/lib/evm_chain_client.dart
- cw_evm/lib/evm_chain_wallet.dart
- cw_polygon/lib/default_polygon_erc20_tokens.dart
- cw_polygon/lib/polygon_client.dart
- cw_polygon/lib/polygon_wallet.dart
> CW-1086: Polygon Issues

- cw_ethereum/lib/deuro/deuro_savings.dart
This PR uses the cake Wallet frontend code for deuro
> Use cakewallet frontend code

- lib/core/fiat_conversion_service.dart
- lib/view_model/dashboard/dashboard_view_model.dart
> feat(tor): add Tor endpoints for fiat-api and service-api

- cw_bitcoin/lib/bitcoin_wallet_addresses.dart
- cw_bitcoin/lib/payjoin/payjoin_send_worker.dart
- lib/view_model/payjoin_details_view_model.dart
Improve handeling of Payjoin Errors and add some more details to payjoin screen
> Generic fixes for payjoin

- cw_ethereum/lib/deuro/deuro_savings.dart
- cw_evm/lib/evm_chain_exceptions.dart
- lib/src/screens/integrations/deuro/savings_page.dart
- lib/src/screens/unspent_coins/unspent_coins_list_page.dart
- lib/view_model/integrations/deuro_view_model.dart
> Deuro Savings Error Handling

- cw_solana/lib/solana_wallet.dart
- lib/buy/dfx/dfx_buy_provider.dart
fix(cw_solana): signMessage to return properly formatted signature
feat(dfx) add initial support for solana and tron
> feat: DFX support for trx and sol

- cw_tron/lib/tron_client.dart
- lib/exchange/provider/swaptrade_exchange_provider.dart
- lib/exchange/provider/xoswap_exchange_provider.dart
> fix missing headers for xoswap and swaptrade

- cw_bitcoin/lib/bitcoin_wallet_addresses.dart
- cw_bitcoin/lib/payjoin/manager.dart
- lib/view_model/payjoin_details_view_model.dart
> 3&4 fixes for Payjoin

- cw_monero/lib/api/account_list.dart
- cw_monero/lib/api/wallet.dart
fix(cw_monero): wallet not reporting finishing sync
> fix(cw_monero): wallet not reporting finishing sync

- cw_bitcoin/lib/bitcoin_wallet.dart
- cw_bitcoin/lib/bitcoin_wallet_service.dart
- cw_bitcoin/lib/electrum_wallet.dart
- cw_bitcoin/lib/litecoin_wallet.dart
- cw_bitcoin/lib/litecoin_wallet_service.dart
- lib/bitcoin/cw_bitcoin.dart
- lib/core/address_validator.dart
- lib/di.dart
- lib/entities/preferences_key.dart
- lib/store/settings_store.dart
- lib/view_model/buy/buy_sell_view_model.dart
- lib/view_model/settings/silent_payments_settings_view_model.dart
- tool/configure.dart
> Make SP scanning, wallet-specific

- lib/src/widgets/bottom_sheet/info_bottom_sheet_widget.dart
fixes disclaimer text showing by default
> fix: show disclaimer text

- lib/core/reset_service.dart
- lib/di.dart
- lib/main.dart
This error occurs due to the keychain persisting auth data on user devices connected to the same iCloud
> CW-809: Fix iOS iCloud Related Issues

- cw_bitcoin/lib/psbt/v0_finalizer.dart
- scripts/macos/app_config.sh
fix some minor issues in comments
> chore: fix some minor issues in comments

- lib/src/screens/send/send_page.dart
- lib/src/widgets/bottom_sheet/confirm_sending_bottom_sheet_widget.dart
> CW-1147: Confirm Send Button Blank in Accessible Navigation Mode

- cw_solana/lib/pending_solana_transaction.dart
- lib/core/open_crypto_pay/open_cryptopay_service.dart
- lib/view_model/send/send_view_model.dart
Add Solana and Tron support for Open Crypto Pay
> feat: Add solana to Open Crypto Pay

- lib/cake_pay/src/models/cake_pay_card.dart
> set minimum card amount to 10 USD

- lib/src/screens/dev/moneroc_call_profiler.dart
This fixes initial build of monero profiler
> fix(dev): monero profiler initState build

- cw_core/lib/utils/proxy_wrapper.dart
- cw_core/lib/utils/tor/abstract.dart
- cw_core/lib/utils/tor/android.dart
- cw_core/lib/utils/tor/disabled.dart
- cw_core/lib/utils/tor/socks.dart
- lib/src/screens/dev/network_requests.dart
- lib/utils/feature_flag.dart
- lib/utils/tor.dart
> feat: CakeTorSocks respect SOCKS_SERVER

- cw_monero/lib/api/coins_info.dart
- cw_monero/lib/monero_wallet.dart
Fixes setting isFrozen on native monero side.
> fix: key image comparision

- ios/Runner/InfoBase.plist
Fixes regression introduced in doge pr
> fix: syntax error in InfoBase.plist

- cw_bitcoin/pubspec.lock
- cw_bitcoin/pubspec.yaml
- pubspec_base.yaml
> fix: uneven hex split for coldcard

- lib/src/screens/base_page.dart
Fixes https://x.com/exitnode_/status/1958749044878070129
> Add SafeArea to base page

- cw_tron/lib/tron_wallet_service.dart
> CW-1203: Tron Wallets Clear its Tokens

- lib/src/screens/base_page.dart
> CW-1185: Bottom Nav Bar Issues

- lib/core/node_port_validator.dart
- lib/src/screens/nodes/widgets/node_form.dart
- lib/view_model/node_list/node_create_or_edit_view_model.dart
- Allow adding new nodes without port
- Replace default port number for empty string when there's no port added
> CW-1204: Node getting deleted/unselected

- lib/view_model/dashboard/home_settings_view_model.dart
> CW-1205: Adding Tokens throws Error

- lib/cake_pay/src/cards/cake_pay_buy_card_page.dart
> CW-1216-Display-the-correct-fiat-value-in-cakepay-cards-purchase

- cw_mweb/android/src/main/jniLibs/.gitignore
Ignore ffi mwebd build outputs to prevent accidentally commiting binary files
> fix: don't include mwebd build outputs

- cw_bitcoin/pubspec.lock
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> fix mweb build on iOS

- cw_ethereum/lib/ethereum_transaction_info.dart
- cw_ethereum/lib/ethereum_wallet.dart
- cw_evm/lib/evm_chain_transaction_info.dart
- cw_polygon/lib/polygon_transaction_info.dart
- cw_polygon/lib/polygon_wallet.dart
- lib/polygon/cw_polygon.dart
> fix: Polygon transactions not coming up in transactions history page

- cw_bitcoin/pubspec.yaml
Use fixed version of Payjoin and sp_scanner
> chore: update dependencies in  cw_bitcoin

- cw_core/lib/window_size.dart
> fix: Tentative fix for windowsize missing plugin exception

- lib/src/screens/send/send_page.dart
> CW-1168-Prevent-sending-a-transaction-twice-by-mistake

- scripts/linux/app_config.sh
> fix: override flutter_secure_storage on linux

- lib/src/screens/connect_device/connect_device_page.dart
> refactor: center ConnectDevicePage

- lib/src/screens/restore/wallet_restore_from_keys_form.dart
- lib/view_model/restore/restore_wallet.dart
feat: handle `label` restore field from cupcake
> CW1173: cupcake enhancements
